### ISSUE TITLE
direct mode: round down to region alignment

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#1002]
The current GetCapacity implementation in direct mode (= pmd-ndctl.go) does not consider fragmentation. It needs to know about that to calculate the maximum volume size correctly.

**Comment by pohly** [comment]
`ndctl_region_get_max_available_extent()` returns the intended value.

**Comment by pohly** [comment]
Not directly related, but the same code also needs to be updated to account for alignment with the region alignment.

**Comment by pohly** [comment]
Ahem. It is already using that:
```
available := r.MaxAvailableExtent()
```

So what remains to be done is just the alignment update.

**Comment by okartau** [comment]
recent size and align improvement PR added down-aligning there by region alignment. Note however that we added alignment fix in creation by LCM of two alignment, combining 2 align values is not done now in GetCapacity.
