### ISSUE TITLE
make "test_e2e" does not pass

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#101]
more details to be added, to be investigated and fixed

**Comment by okartau** [comment]
I started to try this; with 3 small code changes test_e2e compiles, and run will show:
Ran 34 of 59 Specs in 1882.723 seconds
FAIL! -- 32 Passed | 2 Failed | 0 Pending | 25 Skipped

I wonder what really takes 1882 seconds there, waiting for timeouts?
e2e test seems to be based on csi-sanity.
In unified mode, simple csi-sanity runs about 5 seconds
and reports `SUCCESS! -- 33 Passed | 0 Failed | 0 Pending | 25 Skipped`

**Comment by pohly** [comment]
E2E includes csi-sanity, but also runs tests using the Kubernetes API (creating a PVC, starting a POD, etc.).

Some of the upstream tests are indeed written badly in the sense that they wait five minutes for an error, which is then considered a test success (https://github.com/kubernetes/kubernetes/issues/71748). I'm not sure whether the current revision of the testsuite actually includes those - as you are seeing real failures, it's more likely that pod scheduling failed.

A full log should show that.

**Comment by okartau** [comment]
I started to look at e2e remaining failures, at least one is caused by missing path as deploy/kubernetes/ got renamed to path wit explicit version number => #158

**Comment by okartau** [comment]
state is even better, just one failure remains after I made sure all deployment files have replaced registry address. (this is on top of direct-nvdimm branch plus #158)

**Comment by okartau** [comment]
Remaining one failure is caused by:
- Mount,Stage directories are created on node-1
- NodeStageVolume is attempted on different node, node-2 where controller-0 runs
(as in Unified mode controller-0 performs NodeStageVolume operations

**Comment by okartau** [comment]
After recent improvement in numerous PRs make test_e2e now works and sanity test result is:
SUCCESS! -- 35 Passed | 0 Failed | 0 Pending | 26 Skipped
--- PASS: TestE2E (1666.82s)
PASS
ok      github.com/intel/pmem-csi/test/e2e      1666.881s

I propose we close this issue now and open new issues for future work,
or is there something else we could cover under this issue?

**Comment by pohly** [comment]
This really was only about test failures. Let's close it.
