### ISSUE TITLE
Unable to build images: Go too old

### ISSUE THREAD

**Issue by devimc** [intel/pmem-csi#1013]
```
$ make build-images 
go mod tidy
warning: ignoring symlink /home/juliomon/pmem-csi/cmd/manager
github.com/intel/pmem-csi/deploy imports
	embed: package embed is not in GOROOT (/usr/local/go/src/embed)
Makefile:118: recipe for target 'populate-vendor-dir' failed
make: *** [populate-vendor-dir] Error 1
````

Golang version >= 1.16 is required to build the images, is this documented somewhere?  if not, should this be documented?

cc @pohly

**Comment by pohly** [comment]
It can be seen in `go.mod` and the `Dockerfile`.

We don't expect users to build from source, so we don't document the necessary steps anymore. The instructions for developers are in docs/DEVELOPMENT.md and that points to the `Dockerfile`.

**Comment by devimc** [comment]
hmmm okay ..

**Comment by pohly** [comment]
We have a warning that normally is triggered once when invoking make which points out a version mismatch for Go. The problem in this case was that `make build-images` doesn't depend on that check. I'll fix that.

**Comment by pohly** [comment]
Warning added in PR https://github.com/intel/pmem-csi/pull/1016
