### ISSUE TITLE
build-images: too many requests: You have reached your pull rate limit

### ISSUE THREAD

**Issue by devimc** [intel/pmem-csi#1036]
We are facing the following error in our Kata Containers CI

```
9:28:32 Sending build context to Docker daemon  62.01MB
19:28:33 Step 1/48 : ARG LINUX_BASE=debian:buster-slim
19:28:33 Step 2/48 : FROM ${LINUX_BASE} AS build
19:28:33 toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
19:28:35 Makefile:98: recipe for target 'build-image' failed
19:28:35 make[1]: *** [build-image] Error 1
19:28:35 make[1]: Leaving directory '/home/jenkins/workspace/go/src/github.com/kata-containers/tests/pmem-csi'
19:28:35 [pmem_test.sh:77] ERROR: make build-images
```
cc @pohly @GabyCT

**Comment by pohly** [comment]
We don't have a solution for this at this time. If you need to pull the image frequently, perhaps mirror it locally?

**Comment by mythi** [comment]
or `--build-arg LINUX_IMAGE=...`?

**Comment by pohly** [comment]
BTW, why are you rebuilding the PMEM-CSI images in your CI?

We publish canary images that went through testing and thus should be more stable than what gets built from "devel".

**Comment by devimc** [comment]
@pohly 

> BTW, why are you rebuilding the PMEM-CSI images in your CI?

the goal of the CI is to check the latest kata (main) and its integration with the latest pmem-csi plugin (devel), we would like to detect any bug asap and fix it or report it, 

thanks @mythi - let me try with `--build-arg LINUX_IMAGE=...`

**Comment by pohly** [comment]
> the goal of the CI is to check the latest kata (main) and its integration with the latest pmem-csi plugin (devel), we would like to detect any bug asap and fix it or report it,

That would be very useful. As we discussed in chat, we can't do that at our end because we don't have workers for our CI where Kata works.

However, by building from source you might run into unrelated issues more often than when using canary. The risk is probably small, I just wanted to mention it. Building from source might (ironically) be more efficient because you can cache the base image while the same might not be as easy for the canary image.

**Comment by devimc** [comment]
thanks @pohly @mythi , closing issues, fixed Kata side

**Comment by pohly** [comment]
@devimc: FYI, the PMEM-CSI images on Docker Hub are no longer rate limited.

**Comment by devimc** [comment]
@pohly great! thanks :+1:
