### ISSUE TITLE
CrashLoopBackOff on node when deploying driver via YAML files

### ISSUE THREAD

**Issue by jebruen** [intel/pmem-csi#1061]
I've followed the instructions in install.md to deploy the driver to my cluster via my selected /deploy/kubernetes-1.XX .yaml file.
`$ kubectl create -f deploy/kubernetes-1.20/pmem-csi-direct-testing.yaml`

After running `$ kubectl get pods -n pmem-csi` I get:

NAME                                             READY   STATUS             RESTARTS   AGE
pmem-csi-intel-com-controller-7db5dbb8f4-2kv7l   1/1     Running            0          85s
pmem-csi-intel-com-node-89lp2                    1/3     CrashLoopBackOff   4          85s

I checked the logs for this node with `kubectl logs pmem-csi-intel-com-node-89lp2 -n pmem-csi --all-containers`

...and got this:

I0103 21:56:17.789556       1 main.go:74] "PMEM-CSI started." version="v1.0.0-55-g0e10a851"
I0103 21:56:17.789730       1 mount_linux.go:163] Detected OS without systemd
I0103 21:56:17.790401       1 mount_linux.go:163] Detected OS without systemd
I0103 21:56:17.792960       1 mount_linux.go:163] Detected OS without systemd
I0103 21:56:17.793591       1 main.go:91] "PMEM-CSI stopped."
failed to run driver: bind-mounting /host-sys to /sys did not result in writable /sys
I0103 21:50:44.988809       1 main.go:113] Version: v2.2.0
I0103 21:50:44.990125       1 main.go:137] Attempting to open a gRPC connection with: "/csi/csi.sock"
W0103 21:50:54.991011       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:51:04.990443       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:51:14.990580       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:51:24.990618       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:51:34.991250       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:51:44.991155       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:51:54.990765       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:52:04.991246       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:52:14.990741       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:52:24.990913       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:52:34.991137       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:52:44.990744       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:52:54.991027       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:53:04.990909       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:53:14.990742       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:53:24.991251       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:53:34.990380       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:53:44.990758       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:53:54.990998       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:54:04.990667       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:54:14.990787       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:54:24.990740       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:54:34.990475       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:54:44.990954       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:54:54.990798       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:55:04.990760       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:55:14.990874       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:55:24.990782       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:55:34.990222       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:55:44.990563       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:55:54.991263       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:04.990517       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:14.990377       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:24.990879       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:34.990899       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:44.990673       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:54.990213       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:57:04.990848       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:57:14.990541       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:55:51.919247       1 feature_gate.go:235] Setting GA feature gate Topology=true. It will be removed in a future release.
I0103 21:55:51.919281       1 feature_gate.go:243] feature gates: &{map[Topology:true]}
I0103 21:55:51.919295       1 csi-provisioner.go:138] Version: v2.2.2
I0103 21:55:51.919314       1 csi-provisioner.go:161] Building kube configs for running in cluster...
W0103 21:56:01.928548       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:11.928764       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:21.927860       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:31.928324       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:41.928750       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:56:51.928793       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:57:01.928454       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:57:11.927922       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0103 21:57:21.928447       1 connection.go:172] Still connecting to unix:///csi/csi.sock

When I run `kubectl describe pod pmem-csi-intel-com-node-89lp2 -n pmem-csi` I get a lot of details, but these fields seemed to be the most valuable in diagnosing the problem:

For pmem-driver container:
 State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Message:      failed to run driver: bind-mounting /host-sys to /sys did not result in writable /sys
      Exit Code:    1

Also under the Events heading there is one warning message:

 Warning  Unhealthy  3m27s (x593 over 13m)  kubelet            Startup probe failed: Get "http://AN_IP_ADDRESS:10011/metrics": dial tcp AN_IP_ADDRESS:10011: connect: connection refused

Thank you for your help!

**Comment by pohly** [comment]
How was Kubernetes installed? Which version of it? Which container runtime?

The problem is exactly this: `bind-mounting /host-sys to /sys did not result in writable /sys`. We are using a workaround to map /sys from the host into the driver container because we encountered Kubernetes distros where accessing /sys directly wasn't possible, but it looks like the workaround also doesn't work in your case.

**Comment by jebruen** [comment]
-Kubernetes was installed on this machine before I began working on it, so I don't know exactly how it was installed. 
-My client version of kubernetes is 1.22.3 whereas my server version is 1.20.7
-My container runtime is containerd 1.5.2
-I setup my kubernetes cluster using kind following [these](https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/k8s-kind.md) instructions. From what I understand, my kubernetes cluster is setup within a docker container.

Thank you for your help. Any suggestions are greatly appreciated.

**Comment by pohly** [comment]
We are testing Kubernetes 1.19 to 1.23 with containerd as runtime on Fedora 34. The cluster gets installed with kubeadm.

You mentioned KinD. This probably explains the issue because KinD needs to simulate multiple nodes on top of a single host. You cannot run PMEM-CSI inside such a "fake" node.

**Comment by jebruen** [comment]
Thank you, I will setup a new cluster manually instead and try pmem-csi again. Have a nice day!
