### ISSUE TITLE
doc: Examples - Cassandra points to non-existent page

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#1068]
This is the gone-away link we refer in examples/cassandra.md:
https://docs.01.org/clearlinux/latest/guides/stacks/dbrs.html
This broken link also seems to cause failure in "make vhtml" and fails CI periodic job.

**Comment by pohly** [comment]
I have a fix for this pending in https://github.com/intel/pmem-csi/pull/1066

We are still stuck merging PRs because OLM is not working.

**Comment by okartau** [comment]
closing, fixed with merge of #1066
