### ISSUE TITLE
need to validate non-default parameters in deployment

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#110]
We need to make sure the implemented parameters work In deployment schemes, and are documented, also (once we get testing functional) that different parameters and their combinations are tried and verified in test cases.
The cases to cover are at least:
* _fsType_  ext4 vs xfs: by default volume becomes ext4. I tried to specify xfs in manifests but did not made it yet (to be clarified, there likely exist a way)
* _erase after_ is driver-specific parameter that can be added to volume create request. We need to document method to add it, plus add test case does it work. So far verified in stand-alone unified case
* _namespace mode_ is driver-specific parameter that can be added to volume create request. Same as above, needs to be documented and verified, so far done in unified case stand-alone lifecycle
* in LVM2 mode only: other-than-default (which is fsdax=100 % and sector=0% ) allocation of  device space to fsdax and sector mode pools

**Comment by okartau** [comment]
`fsType: xfs` can be demonstrated by adding this to end of currently used  deploy/kubernetes-1.13/pmem-storageclass.yaml:
```
parameters:
  fsType: xfs
```

What about idea to add 2nd storageclass and 2nd respective volume in example deployment so that one is ext4 and another xfs formatted. Then we can demonstrate with same set of commands that both variants work.

**Comment by okartau** [comment]
driver-specific parameters can be used in deployment in same way, added to storageclass, example:
```
parameters:
  fsType: xfs
  eraseafer: "false"
  nsmode: fsdax
```
This solves the question "how to deploy". There is still remaining part: should cover use of different options in deployment example and in tests, and to verify the expected results.

**Comment by okartau** [comment]
Current deploy example completely hides the possibility to use driver parameters. For example, ext4 vs xfs file system choice is not specified or even commented. The result is, ext4 is picked by driver as default, xfs will never be tried or tested. Also, user looking to document and deployment examples, gets no ideas how to specify different file system type.
One possibility to help is to include two volumes in example deployment, one with ext4 and another with xfs. (Can we put 2 different storage classes in single yaml file? also, two pvcs?).
That would mean, we will specify fsType in both parallel storage examples.
The downside of this is, if we want to keep already parallel deployment example structure for -cache volumes consistent, we either have to repeat ext4/xfs dual volumes there, or leave it with default (ext4), or leave it with one but specifying fsType. Which of these is the best?

**Comment by okartau** [comment]
The similar story actually for nsmode: fsdax vs sector parameter, to get it covered, we should add it to deployment example and/or documentation.
eraseafter: same, but perhaps deployment not needed, just documentation

**Comment by okartau** [comment]
eraseafter is no covered by example depaloyment, as it is set to different state in ext4 and xfs cases.
fsdax vs sector mode thus remains uncovered.
We can spread fsdax and sector modes in deployment examples as well, but there is also risk that
if someone bases real deployment on examples, the (typically unneeded) sector case will sneak in.
This is especially true if LVM-mode is used as it involves pre-alloc of sector-mode pool by pmem-ns-init. Testing sector mode is less intrusive for examples if we do it in direct mode, where it does not require pre-allocation of namespaces. But then again, default deployment mode is LVM which conflicts that idea.

**Comment by pohly** [comment]
We can't cover all cases with our examples. At some point we'll simply have to have a CI that runs through various combinations.

**Comment by okartau** [comment]
Yes, I agree. Let's call current support in deployment examples reasonable level of coverage, that's about what I was after when I created this issue. I propose we can close this.

**Comment by pohly** [comment]
Agreed, let's close.
