### ISSUE TITLE
Context.CreateNamespace hides error from lower level calls

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#115]
I spotted this while running util/csi-sanity.sh against unified mode stand-alone pmem-csi in drivermode=ndctl (i.e. bypassing LVM2).
Volume creation sometimes fails in that test like this:
```
GRPC request: name:"sanity-node-full-836087B2-33695F1A" volume_capabilities:<mount:<> access_mode:<mode:SINGLE_NODE_WRITER > > 
CreateVolume: Name: sanity-node-full-836087B2-33695F1A, req.Required: 4194304 req.Limit; 0
CreateVolume: Special create volume in Unified mode
setting namespace sector size ...: 0
setting pfn
rpc error: code = Internal desc = CreateVolume: failed to create volume: Failed to create namespace
```
Here the only information given is "Failed to create namespace" without pointing out which phase of creation actually failed. In Region.CreateNamespace() there is some trace ("setting..." prints) but real error remains hidden, although it is available in `err` that returned from lower calls.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:

> Seems we lose original lower-layer error in ndctl.go in Context.CreateNamespace
> where return stmt creates a new error message, losing the err that was
> returned from failed call.

https://github.com/pkg/errors is a solution for that: always add
additional information to existing errors with errors.Wrap() when
returning a new error.

**Comment by okartau** [comment]
resolved via fixes coming from merge of direct-nvdimm mode in #133
