### ISSUE TITLE
Create public images for pmem-csi containers

### ISSUE THREAD

**Issue by ss7pro** [intel/pmem-csi#142]
We should not be referring to private docker registries. All deployment files should be in a state that anyone can deploy pmem-csi driver without any changes.

https://github.com/intel/pmem-CSI/blob/596f199ff2f4159b03937ad83619e3d150c39402/deploy/kubernetes/pmem-csi.yaml#L101

**Comment by josepalafox** [comment]
Got best practices from the Clear team for releasing this as a clear container. Should be an output of our CI published to docker hub. Will update with more details as we start automating builds for this.

**Comment by pohly** [comment]
v0.5.0 images are now on https://hub.docker.com/u/intel
