### ISSUE TITLE
Cluster deployment fails using Devicemode:Direct

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#167]
Cluster deployment used to work when we merged the devicemode:direct code into devel, just short while ago. But something has changed after that. Now on a recent qemu-based test cluster, with Clear=27660 and Kubernetes=1.13.3, a pmem-csi-driver node pod will not start if /dev hostpath is passed into it (and that volumemount addition was the key turn point which made devicemode:direct deployment working).
Error msg is:
```
Error: failed to start container "pmem-driver": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/3fd0ec14-2ac5-11e9-8362-deadbeef0100/containers/pmem-driver/fd9b54f9\\\" to rootfs \\\"/var/lib/docker/overlay2/17c0636357f4c679d588d8a448c752ec5496271a74d682aee58382d513891a8e/merged\\\" at \\\"/var/lib/docker/overlay2/17c0636357f4c679d588d8a448c752ec5496271a74d682aee58382d513891a8e/merged/dev/termination-log\\\" caused \\\"no such file or directory\\\"\"": unknown
```

**Comment by okartau** [comment]
I wonder is this related to terminationMessagePath ?
terminationMessagePath: /dev/termination-log
but why started to fail just recently?

**Comment by okartau** [comment]
indeed, the problem does not happen if I add this to pod spec,
mapping termination message path under /tmp instead of /dev:
`terminationMessagePath: /tmp/termination-log`

next question, is this safe thing to do, or does it create some additional trouble.
At least mount entries appear for /tmp/termination-log, seems k8s handles this changed path.

**Comment by pohly** [comment]
This looks like a regression in Clear Linux. Current master of pmem-csi works fine on Clear Linux 27500. Changing the `terminationMessagePath` is just a workaround, the default needs to work.

Where did you find this error message with "failed to start container"? I tried with Clear Linux 
27670, and there the controller fails to start because of "Pod sandbox changed, it will be killed and re-created":
```
$ kubectl get pods
NAME                    READY   STATUS              RESTARTS   AGE
pmem-csi-cdxz6          1/2     CrashLoopBackOff    22         91m
pmem-csi-controller-0   0/4     ContainerCreating   0          91m
pmem-csi-npgwp          1/2     CrashLoopBackOff    22         91m
pmem-csi-rl7t2          1/2     CrashLoopBackOff    22         91m
$ kubectl describe pod/pmem-csi-controller-0
Name:               pmem-csi-controller-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               host-3/192.168.8.8
Start Time:         Fri, 08 Feb 2019 08:26:03 +0100
Labels:             app=pmem-csi-controller
                    controller-revision-hash=pmem-csi-controller-7bc9cb59dd
                    statefulset.kubernetes.io/pod-name=pmem-csi-controller-0
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      StatefulSet/pmem-csi-controller
Containers:
  driver-registrar:
    Container ID:  
    Image:         quay.io/k8scsi/driver-registrar:v0.4.1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --mode=kubernetes-register
      --driver-requires-attachment=true
      --pod-info-mount-version=v1
      --csi-address=$(ADDRESS)
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      ADDRESS:  /csi/csi-controller.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-service-account-token-2999j (ro)
  external-provisioner:
    Container ID:  
    Image:         quay.io/k8scsi/csi-provisioner:v0.4.1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --provisioner=pmem-csi
      --csi-address=$(ADDRESS)
      --feature-gates=Topology=true
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      ADDRESS:  /csi/csi-controller.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-service-account-token-2999j (ro)
  external-attacher:
    Container ID:  
    Image:         quay.io/k8scsi/csi-attacher:v0.4.1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=$(ADDRESS)
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      ADDRESS:  /csi/csi-controller.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-service-account-token-2999j (ro)
  pmem-driver:
    Container ID:  
    Image:         192.168.8.1:5000/pmem-csi-driver:canary
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      -v=5
      -drivername=pmem-csi
      -mode=controller
      -endpoint=$(CSI_ENDPOINT)
      -registryEndpoint=$(REGISTRY_ENDPOINT)
      -nodeid=$(KUBE_NODE_NAME)
      -caFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      -certFile=/certs/pmem-registry.crt
      -keyFile=/certs/pmem-registry.key
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      REGISTRY_ENDPOINT:  tcp://0.0.0.0:10000
      CSI_ENDPOINT:       unix:///csi/csi-controller.sock
      KUBE_NODE_NAME:      (v1:spec.nodeName)
    Mounts:
      /certs/ from registry-cert (rw)
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-service-account-token-2999j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  socket-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins/pmem-csi/
    HostPathType:  DirectoryOrCreate
  registry-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pmem-registry-secrets
    Optional:    false
  csi-service-account-token-2999j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  csi-service-account-token-2999j
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason          Age                  From             Message
  ----    ------          ----                 ----             -------
  Normal  SandboxChanged  69s (x418 over 91m)  kubelet, host-3  Pod sandbox changed, it will be killed and re-created.
```

**Comment by pohly** [comment]
The example from https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/#writing-and-reading-a-termination-message can be used to reproduce the problem.

**Comment by okartau** [comment]
> Current master of pmem-csi works fine on Clear Linux 27500.

Based on shown options, you deploy pmem-csi in devicemode:lvm, so our use cases are different.
My deployment (my bad I left out details in original issue text) is in devicemode:direct i.e. you use deploy/kubernetes-1.13/pmem-csi-direct.yaml  instead of deploy/kubernetes-1.13/pmem-csi.yaml.
There is added passing of /dev and that seems to cause the error I saw.

> Where did you find this error message with "failed to start container"?

The error was in Events: section of "describe pod"

**Comment by pohly** [comment]
So I'm running into something else then.

**Comment by pohly** [comment]
I can no longer reproduce the "Pod sandbox changed, it will be killed and re-created." error. I made some changes (see https://github.com/intel/pmem-CSI/pull/169) but that seems unrelated.

**Comment by pohly** [comment]
Regarding `terminationMessagePath`: if the pod spec causes `/dev` to be treated differently, then I think it is reasonable to also change the `terminationMessagePath` default. My understanding is that the default assumes that `/dev/terminationMessagePath` is a file in the overlay of the container. Mounting the host's `/dev` breaks that assumption.

But is `/tmp` an actual directory in the filesystem or a tmpfs? `/var/tmp` might be better. In the end it doesn't matter, because nothing in our containers writes into that file, right?

**Comment by okartau** [comment]
> But is `/tmp` an actual directory in the filesystem or a tmpfs? `/var/tmp` might be better. In the end it doesn't matter, because nothing in our containers writes into that file, right?

in pmem-csi plugin container: /tmp and /var/tmp are both on overlay FS i.e. on host file system, i.e. not in tmpfs. 
in a host running this container (Clear): /tmp is on tmpfs and /var/tmp is in rootfs

**Comment by okartau** [comment]
I can not reproduce on currently created 'make start' VMs , Clear version 28030, let's close this
