### ISSUE TITLE
E2e uses hard-coded labels and IPs

### ISSUE THREAD

**Issue by chuyd** [intel/pmem-CSI#178]
To provide end-to-end continuos integration we require to have flexible ips and labels. Right now the images are being pulled from the `192.168.8.1` and the tests requires a kubernetes node with the label `host1`  with the ip `192.168.8.2`. The e2e is requiring the `make start` to create the `_work/ssh-clear-kvm.1` sh script to connect through ssh to the ip specified before.

To consume the e2e i  workaround it replacing the IPs and nodes:
```
grep -r 192.168.8.1 -l | xargs -L  1 sed -i "s|192.168.8.1|$MASTER_NODE_IP|g"
grep -r 192.168.8.2 -l | xargs -L  1 sed -i "s|192.168.8.2|$WORKER_NODE_IP|g"
grep -r canary -l | xargs -L 1 sed -i "s|canary|$BUILD_ID|g"
grep -r host-1 -l | xargs -L 1 sed -i "s|host-1|$KUBE_WORKER_NODE|g"
```
Maybe  we could use flags or environment variables in order to have an agnostic k8s ci.

**Comment by pohly** [comment]
You can already drop a file into https://github.com/intel/pmem-CSI/tree/devel/test/test-config.d to configure some of these settings, like the IP addresses. But the e2e.test binary itself doesn't read those settings, it's more for the "make start" command.

Configuring the e2e.test binary would have to be done via additional command line flags.

Replacing "canary" is for the deployment, right? That and fixing the registry address in the .yaml files is something that you can do as part of your driver deployment.

Can you work on this yourself as you run into specific situations where something must be made more flexible and then submit a PR?
