### ISSUE TITLE
README should emphasize more clearly what is built for which purpose

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#179]
As recent learning from "freshly joined developer standpoint":
When one takes README and goes step-by-step, it's no clearly documented that
local/standalone build (make) is not needed to reach cluster deployment,
if one chooses, local build stage can be skipped altogether.
Local build is only meaningful in some development stages if local changes can be verified
using locally-built and started binaries.

**Comment by okartau** [comment]
I tried to achieve by adding of DEVELOPMENT.md file in #181 
This new file should contain dev-mode information, leaving production and deployment level for README, thus keeping different build commands, unified mode, stand-alone instructions (etc. such topics) apart from each other.

**Comment by adnavare** [comment]
@okartau: Thanks for creating this issue.

**Comment by adnavare** [comment]
FYI, I found two more things that might be helpful if noted
I also made changes to the Makefile to have '--network host' added while building docker images using "make build-images". Otherwise for me when I tried to build the images it complained about Alpine Linux 3.9 not getting updated with apk. I root caused that the containers were unable to reach to the network and host was not passing the proxies.  

While pushing the image, "make push-images" I had to start the local registry first using "docker run -d -p 5000:5000 --restart=always --name registry registry:2" and then push to avoid "connection refused" errors that I encountered initially. 

Do you think this would be good to point somewhere?

**Comment by okartau** [comment]
> I also made changes to the Makefile to have '--network host' added while building docker images using "make build-images". Otherwise for me when I tried to build the images it complained about Alpine Linux 3.9 not getting updated with apk. I root caused that the containers were unable to reach to the network and host was not passing the proxies.

Current support for building behind proxy has 2 choices:
- proxy values defined as env.variables, see Makefile, these are passed into docker build only if set.
- proxy values defined in user home dir, like ~/.docker/config.json, this should also work.
So far these methods have been sufficient and we haven't need other options to docker build

**Comment by adnavare** [comment]
@okartau : You are right, I looked this up in the Makefile and the env variables were getting added as BUILD_ARGS but still apk update was failing. Adding the proxies in config.json also didn't help. After adding --network host it resolved.

**Comment by okartau** [comment]
> While pushing the image, "make push-images" I had to start the local registry first using "docker run -d -p 5000:5000 --restart=always --name registry registry:2" and then push to avoid "connection refused" errors that I encountered initially.

having a functional registry somewhere has been kind of implicit requirement, registry starting instructions not stated explicitly as that is kind of out of scope, also there are various different ways/locations to run a registry, developer vs. production, secure vs. insecure, local vs. remote,
documenting all this would need another chapter or two.
But I agree, adding some notes would make this more user-friendly.

**Comment by okartau** [comment]
> @okartau : You are right, I looked this up in the Makefile and the env variables were getting added as BUILD_ARGS but still apk update was failing. Adding the proxies in config.json also didn't help. After adding --network host it resolved.

That's interesting. You are still on Ubuntu 18.04, right. What is docker version?
Also "host is resolved" points towards name resolution issue instead of proxy issue?

**Comment by adnavare** [comment]
> > While pushing the image, "make push-images" I had to start the local registry first using "docker run -d -p 5000:5000 --restart=always --name registry registry:2" and then push to avoid "connection refused" errors that I encountered initially.
> 
> having a functional registry somewhere has been kind of implicit requirement, registry starting instructions not stated explicitly as that is kind of out of scope, also there are various different ways/locations to run a registry, developer vs. production, secure vs. insecure, local vs. remote,
> documenting all this would need another chapter or two.
> But I agree, adding some notes would make this more user-friendly.

Yes you are right! This might be something not related to the plugin and kind of scope. I agree it was just FYI.

**Comment by adnavare** [comment]
@okartau : docker version is 18.06. Yes it seems to be about name resolution and not proxies but then proxies itself is not enough and name resolution is something that needs to be taken care as well.
