### ISSUE TITLE
add unique version number to each build

### ISSUE THREAD

**Issue by pohly** [intel/pmem-CSI#183]
When looking at a running cluster it is impossible to tell which revision of the pmem-csi driver is running. Let's build a unique version string into the binary with a `-version` flag (as in https://github.com/intel/oim/commit/e38285d4729b80c56c8107aa4e9f730658ade13b) and in addition, always print that when the driver runs (currently missing in OIM).

**Comment by okartau** [comment]
excellent point, must-to-have for tracking and clarity!
One question: driver currently already carries version information which is now hard-coded to "0.0.1", and used as response to "CSI identity plugin-info", here reported by driver in unified mode:
```
$ csc identity plugin-info
"pmem-csi"      "0.0.1"
```

But this information is not utilized in ways we consider useful for development, right?
- shown in output/log when driver starts
- recorded as part of csi-sanity output

Does the pointed OIM method create a parallel version tracking mechanism to plugin-info, or does it
overwrite the existing one, and if parallel, should we try to unify those two version records?

**Comment by okartau** [comment]
I was too pessimistic about "not utilized", plugin-info query is performed near end of `make test_e2e`  we run now (part of csi-sanity, right):
```
pmem-csi-unified-0/pmem-driver: Using default GetPluginInfo
pmem-csi-unified-0/pmem-driver: GRPC response: name:"pmem-csi" vendor_version:"0.0.1" 
```

**Comment by pohly** [comment]
In OIM there is just one version, and GetPluginInfo reports that.

**Comment by okartau** [comment]
What is the plan or example of `-version` flag use (in running cluster, or overall)? Do I have to create/modify deployment file adding `-version` flag, deploy the container, and look to log files?
What is is the likelyhood anybody really doing that in practice? And what's the advantage of that compared to deployment without -version flag, in case we print the version always during start (what we should do).
My point is, if the only running method is deployment from registry, then cmd-line style `-version` flag is not so useful/easy to use, so is it worth the effort of adding it.
Is it enough to just add print of version in startup log of every component we have, and report same info via plugin-info API.

I think in real deployments, version gets fixed to some value via deployment file, so user/admin will not re-check it anyway (or does it from logs). That leaves development-time use for version string,
and that is also much better covered via log file use, or trace in csi-sanity report file.

**Comment by avalluri** [comment]
@okartau  I implemented the versioning as make variable, by default it generates version from git.
