### ISSUE TITLE
E2E tests for cache volume

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#212]
None of the current tests cover the special aspects of cache volumes. We need an E2E test that ensures that:
- each node stores its own data separately
- each node has a volume of the expected size
- data is retained across app restarts
- has the right topology information

**Comment by avalluri** [comment]
@pohly #196 covers tests for cache volume with state persistency on node restart. Do you think anything more to add in the context of this issue?

**Comment by pohly** [comment]
Amarnath Valluri <notifications@github.com> writes:
> @pohly #196 covers tests for cache volume with state persistency on
> node restart. Do you think anything more to add in the context of this
> issue?

Yes, we could add testing of more corner cases:
- creating more instances than we have nodes
- asking for a volume size that is too big

Let's keep open for now, but without considering it a blocker for 1.0.

**Comment by avalluri** [comment]
> - creating more instances than we have nodes

@pohly What is the expected results in this case.

> - asking for a volume size that is too big

How does this case specific to cache volume?

**Comment by pohly** [comment]
I think we have tests specific to cache volumes.
