### ISSUE TITLE
LVM-mode: ext4 mount with -o dax fails on Clear VM in e2e test

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#225]
`make test_e2e` fails in recent test clusters, if devicemode=lvm,
Same test works if devicemode=direct.
These have been verified to fail:
k8s=1.13.5 (Clear few steps older than 28640, I did not record)
Clear=28640 k8s=1.14, kernel 5.0.6

There are mount errors:
```
Executing: mount -c -o dax /dev/ndbus0region0fsdax/107eea56-56cc-11e9-93d6-36feaaf12372 /var/tmp/tmp.bvQWXy7mlR/staging
mount: /var/tmp/tmp.bvQWXy7mlR/staging: wrong fs type, bad option, bad superblock on /dev/ndbus0region0fsdax/107eea56-56cc-11e9-93d6-36feaaf12372, missing codepage or helper program, or other error.
```

The error is reproducible on plain VM CLI as well. It turns out that failure happens when `-o dax` is added, and file system type is ext4 (That's the one used by e2e test).
I can mount xfs-formatted file system with dax option without error (but it has to be bigger than 1M or 4M which is used by e2e testing, for mkfs.xfs even considering making file system).

This used to work short time ago so seems to be caused by a recent change.
@pohly verified e2e test works on his cluster which is Clear=28070

**Comment by okartau** [comment]
Another finding: In a new cluster created with 'make start', example deployment succeeds.
The code has #222 and #224 changes applied on top of current devel branch. That means one ext4 and one xfs volume get provisioned OK in LVM mode, with dax option added. 
Then I run 'make test_e2e' in same cluster, and in that test mount of ext4 volumes fails as described in this issue. There is something different in e2e mounts than example deployment mount. Smaller volume size ?

**Comment by pohly** [comment]
It is pretty small: https://github.com/intel/pmem-CSI/blob/410910868c78ccf0e311ff1f7c9111fed77f78fc/test/e2e/storage/csi_volumes.go#L110

**Comment by okartau** [comment]
Confirmed that mount works for larger volume (4GB) and fails for smaller (1MB).
On a VM tester host (Clear 28780, kernel 5.0.7), without pmem-csi driver involved, just CLI:

4GB size used by example deployment, **mount works**:
```
root@host-2 ~ # lvcreate -L4g -n v1 ndbus0region0fsdax
  Logical volume "v1" created.
root@host-2 ~ # mkfs.ext4 /dev/ndbus0region0fsdax/v1
mke2fs 1.44.5 (15-Dec-2018)
Creating filesystem with 1048576 4k blocks and 262144 inodes
Filesystem UUID: 7077eff5-89b7-47c5-b4f0-7853c59fda8d
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

root@host-2 ~ # mount -o dax /dev/ndbus0region0fsdax/v1 /mnt
```

1MB size used by e2e, **mount fails**:
```
root@host-2 ~ # lvcreate -L1m -n v2 ndbus0region0fsdax
  Rounding up size to full physical extent 4.00 MiB
  Logical volume "v2" created.
root@host-2 ~ # mkfs.ext4 /dev/ndbus0region0fsdax/v2
mke2fs 1.44.5 (15-Dec-2018)
Creating filesystem with 4096 1k blocks and 1024 inodes

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (1024 blocks): done
Writing superblocks and filesystem accounting information: done

root@host-2 ~ # mount -o dax /dev/ndbus0region0fsdax/v2 /mnt
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/mapper/ndbus0region0fsdax-v2, missing codepage or helper program, or other error.
```

**Comment by okartau** [comment]
ext4 file system block size is key to mount failure.
Creating filesystem with 1048576 **4k blocks** and 262144 inodes
Creating filesystem with 4096 **1k blocks** and 1024 inodes

If omitted in calling options, mkfs.ext4 selects block size heuristically determined by the filesystem size.
It is selected 4k for larger system and switches to 1k somewhere between 512M and 256M.
When forced to 4k in smaller system, mount will succeed.
When forced to 1k in larger system, mount will fail.

There is way to make it heuristic but guarantee at last min.value of 4k: using mkfs.ext4 -b -4096
i.e. prepending dash to size. This could help our driver LVM mode in small systems

**Comment by okartau** [comment]
If we look at explained examples at
https://pmem.io/2018/05/15/using_persistent_memory_devices_with_the_linux_device_mapper.html
there all ext4 formatting examples just use hard-coded, forced block size: -b 4096 so that no heuristics is allowed. Should we do same, is 4096 enough static value that we can hard-code it?
Or, another way is to look up block size from lower layers, for example with lsblk, and use same value. That would avoid hard-coding numeric value.
