### ISSUE TITLE
record termination message

### ISSUE THREAD

**Issue by pohly** [intel/pmem-CSI#233]
When the PMEM-CSI driver encounters a fatal problem, it should write an explanation to the termination log file before quitting. That way, `kubectl describe pods` can show the reason why the container is no longer running.

One example is `Failed to run driver: FATAL: /sys mounted read-only, can not operate`.

**Comment by okartau** [comment]
Do I get it right that pod can't determine at run time what is value of its **terminationMessagePath** property? And therefore it has to use hard-coded value for this? In that case we better unify terminationMessagePath value (is different now) in direct vs lvm mode.
Side question: if we use non-default terminationMessagePath  can we define single source of that  used by deployment file(s) and driver source? Can kustomize perhaps help there?

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:

> Do I get it right that pod can't determine at run time what is value
> of its **terminationMessagePath** property?

I think that's correct.

> And therefore it has to use hard-coded value for this? In that case we
> better unify terminationMessagePath value (is different now) in direct
> vs lvm mode.

We could introduce an env variable that gets set as part of the
deployment. Probably cleaner than hard-coding a default into the
binaries.

> Side question: if we use non-default terminationMessagePath can we
> define single source of that used by deployment file(s) and driver
> source? Can kustomize perhaps help there?

With kustomize, we can put the non-standard termination path into the
common base, so it won't be duplicated.

**Comment by okartau** [comment]
Seems we still have to repeat the path few times, as terminationMessagePath= declaration seems not able to take value from declared env.variable. I will post PR soon with code I got working.
