### ISSUE TITLE
restrict merging to "merge with merge commit"

### ISSUE THREAD

**Issue by pohly** [intel/pmem-CSI#255]
"merge with merge commit" has several advantages:
- When a PR contains multiple changes, they land on "devel" as a single change, which is useful for bisecting.
- The development history is preserved, which can be relevant; for example, https://github.com/intel/pmem-CSI/pull/239 was developed in parallel to https://github.com/intel/pmem-CSI/pull/228 and then not merged correctly (rebased by GitHub without re-running `make kustomize`). This is not visible in the git history, so understanding the root cause of the inconsistent deployment files was harder than it would have been otherwise. So even for PRs with a single commit a merge commit is useful.

Proposal: always use merge commits and enforce that via GitHub settings (need to ask admins to make that change for us).

@okartau, @avalluri: agreed?

**Comment by okartau** [comment]
I agree, let's use "merge commit" mode.
I can't modify repo settings, so yes we need admin's help.

**Comment by avalluri** [comment]
I agree to use merge commits.

**Comment by pohly** [comment]
Done by our repo admins.
