### ISSUE TITLE
Retire unified mode

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#256]
We can get rid of unified mode. This is tracking/discussion issue to make sure we cover all related parts.
These can be removed/cleaned:
- "unified" as one choice of DriverMode in code, comments, command line options
- Description in documents: README.md DEVELOPMENT.md
- unified mode specific deployment files and referral from other deployment files
- Retire README-qemu-notes.md as we should not promote setting up single Qemu-based dev.env, which was in early project days used in unified mode. If there are useful bits in there worth survival, we can move those into DEVELOPMENT.md
- Remove the entire test/sanity directory, has been superseded by `test/e2e/storage/sanity.go`
- unified-mode scripts in `util/`

**Comment by okartau** [comment]
test/sanity/sanity_test.go still uses mode=unified, so we cant retire it yet?

**Comment by pohly** [comment]
`test/sanity/sanity_test.go` has been superseded by `test/e2e/storage/sanity.go`. We can remove the entire `test/sanity` directory.

**Comment by okartau** [comment]
> We can remove the entire `test/sanity` directory.

I added that in 1st comment box to have list of change entries in one place
