### ISSUE TITLE
default namespacesize of 9GB does not make sense on HW-based deployment

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#275]
We have left namespacesize=9GB in example deployment, which has been left there
from dev.times when we used emulated storage.
That size will result in creation of large amount of namespaces on HW-based systems with large devices.
We should put bigger value there.
Note that default is 32GB, which is improvement over 9 GB,
but may also feel too small for multiple hundreds of GB devices.
Nothe that putting a larger value than device size does not cause failure, pmem-ns-init will reduce the actual size to adjust for remaining size, i.e. with large setting we will get
one device-size namespace, which is also not bad for tester systems (with small emulated device)

**Comment by avalluri** [comment]
@okartau maybe its time to reevaluate our design about namespaces in lvm mode, Do we really need to split the nvdimm region and merge back with LVM?. Instead, how about creating a single namespace(per namespace mode) with the size of the region. This simplifies namespace creation logic and even speeds-up driver startup time on Nodes, i feel.

**Comment by okartau** [comment]
I agree, let's go to single namespace. 
The idea behind multiple namespaces was to make the potentially failing unit smaller, also to leave possibility for manual fixes and adjustments in smaller scale (for example, possibility to detach or add device slices in smaller sets).
In production case, none of that has real value, right. We don't expect admin to configure single namespaces and PVolumes. It's actually the opposite, creation of multiple objects adds risk of inconsistency.
There is another way to partition in LVM mode by setting "use for" ratios, and creating one more level by slicing space to many pre-allocated namespaces, is unneeded complexity.

I will prepare a PR replacing many namespaces during pre-allocating with single namespace. It will simplify the code.
