### ISSUE TITLE
Repeated test_e2e degrades cluster ability and leaves many leftover LV volumes

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#280]
I tried to repeat findings of https://github.com/intel/pmem-CSI/pull/278#issuecomment-492104594 but leaving out version change impact.

With code from current head of branch=devel, Clear VM cluster with `make start`,
using devicemode=LVM, repeated `make test_e2e`:

- runs 1..7 PASS
- run 8 FAIL "should fail when no volume capabilities are provided"
- run 9 FAIL "sanity Node Service [It] should work"
- run 10 FAIL "should fail when no volume capabilities are provided"
- run 11 FAIL "should return appropriate values (no optional values added)"

seems repeated e2e runs degrade ability seriously, with errors varying.

Another finding: after 11 rounds, all nodes have leftover LV volumes with 4MB sizes
(so small not affecting provision ability via space exhaustion at least)
- host-1: 63 volumes
- host-2: 42 volumes
- host-3: 7 volumes

**Comment by okartau** [comment]
We can suspect recent change to clear-based containers, but we don't have documented results of repeated e2e from times before container base change. That can be retested taking older code, I think

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:

> I tried to repeat findings of https://github.com/intel/pmem-CSI/pull/278#issuecomment-492104594 but leaving out version change impact.
>
> With code from current head of branch=devel, Clear VM cluster with `make start`,
> using devicemode=LVM, repeated `make test_e2e`:
>
> - runs 1..7 PASS
> - run 8 FAIL "should fail when no volume capabilities are provided"
> - run 9 FAIL "sanity Node Service [It] should work"
> - run 10 FAIL "should fail when no volume capabilities are provided"
> - run 11 FAIL "should return appropriate values (no optional values
> added)"

Is that perhaps because of the volume leak that @avalluri found in
csi-sanity? The fix has been merged, but to get it, one currently has to
update to csi-test master.

> seems repeated e2e runs degrade ability seriously, with errors varying.
>
> Another finding: after 11 rounds, all nodes have leftover LV volumes with 4MB sizes
> (so small not affecting provision ability via space exhaustion at least)
> - host-1: 63 volumes
> - host-2: 42 volumes
> - host-3: 7 volumes

That looks like the leak. However, as there is space left, why are tests
failing?

It sounds like we hit a scalability issue somewhere.

**Comment by okartau** [comment]
I repeated e2e tests 20 times with code at commit c1f09ba2d358124449d6734a5852cf50eb9c6858 i.e. last point before clear-based container was introduced.
1st round failed with
```
      ^[[91m[mktemp -d /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pmem-sanity-target.XXXXXX] in socat container, stderr:
      Unexpected error:
          <exec.CodeExitError>: {
                  s: "command terminated with exit code 126",
          }
```
but next 19 rounds ran error-free.
After 20 rounds, the leftover LV counts:
host-1: 0
host-2: 0
host-3: 6

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:

> I repeated e2e tests 20 times with code at commit c1f09ba2d358124449d6734a5852cf50eb9c6858 i.e. last point before clear-based container was introduced.
> 1st round failed with
> ```
>       ^[[91m[mktemp -d /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pmem-sanity-target.XXXXXX] in socat container, stderr:
>       Unexpected error:
>           <exec.CodeExitError>: {
>                   s: "command terminated with exit code 126",
>           }
> ```

The command took too long. I was discussing this with @avalluri a few
days ago, we should increase the values in the csi-sanity test configuration.

**Comment by okartau** [comment]
good news for this issue: result is much better if tested with changes of #277 applied:
20 x repeated test_e2e with SUCCESS;
after test, leftover LV volumes: 
host-1: 0 volumes
host-2: 1 volumes
host-3: 4 volumes

The repeated failures of "stat: no LV device" are not happening, I think that's because of "wait for device to appear" change, alse mutex change may have contributed. The leftover volumes amount dropped a lot.

**Comment by okartau** [comment]
degraded state and LVM-specific errors (including many-leftover-LVM-volumes) are mixed in this issue with few-leftover-volumes issue, but these seem to have different root causes, and few-leftover-volumes is not LVM specific but also can be seen in direct mode. So I will detach few- leftover-volumes issue from current issue by creating a new one. Then we can handle current issue as LVM-mode specific and get it covered by #277
