### ISSUE TITLE
Multiple issues using LVM-mode on a HW-based system

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#289]
Testing has been mostly happening on emulated devices so far.
Here is some notes resulting from trial on HW-based system.
We may have multiple/cascading issues, so I write down some notes as a start.
Some of issues seem caused by underlying unclean state of namespaces.

Cluster has 3 nodes, one node has 4x128GB of Optane DIMMs organized
as two 256GB regions, interleave_set size is 2.

I tried reference deployment in LVM mode as per README steps.
- too many small namespaces (addressed already in #275, will be resolved by #277).
- volume provisioning fails, timing/race issue?
```
I0521 10:07:57.873824       1 glog.go:58] GRPC call: /csi.v1.Controller/CreateVolume
E0521 10:07:58.205146       1 glog.go:119] FlushDevice: /dev/ndbus0region0fsdax/4ed6ff15-7bb0-11e9-b208-a6ef1e106519 does not exist
E0521 10:07:58.205204       1 glog.go:119] GRPC error: rpc error: code = Internal desc = CreateVolume: failed to create volume: stat /dev/ndbus0region0fsdax/4ed6ff15-7bb0-11e9-b208-a6ef1e106519: no such file or directory
```
After namespace creation completes, corresponding device does not appear in time inside container, but is attempted to flush immediately?
Side question: does this also happen with code before moving to Clear-based container?

This seems to be cause to e2e tests failures/regression that are documented in #280.
Note that repeated e2e hits this in emulated storage as well. But seems to be even more systematic on HW.

Then I stopped driver, tried to get rid of LV state, and destroy all namespaces.
Some namespaces (belonging to same Region) were not deleted after `ndctl destroy-namespace all --force`.
That Region remains in some bad state, as next VG operations start to fail on that:
```
I0521 10:45:10.697547       1 glog.go:58] No Vgroup with name ndbus0region0fsdax, mark for creation
I0521 10:45:10.697569       1 glog.go:58] Executing: vgcreate --force ndbus0region0fsdax /dev/pmem0.10 /dev/pmem0.20 /dev/pmem0.2 /dev/pmem0.12 /dev/pmem0.22 /dev/pmem0.4 /dev/pmem0.6 /dev/pmem0.26 /dev/pmem0.8 /dev/pmem0.1 /dev/pmem0.3 /dev/pmem0.5 /dev/pmem0.7 /dev/pmem0.9
I0521 10:45:10.763600       1 glog.go:58] Output:   Can't open /dev/pmem0.2 exclusively.  Mounted filesystem?
  Can't open /dev/pmem0.4 exclusively.  Mounted filesystem?
  Can't open /dev/pmem0.10 exclusively.  Mounted filesystem?
  Can't open /dev/pmem0.12 exclusively.  Mounted filesystem?
  Can't open /dev/pmem0.20 exclusively.  Mounted filesystem?
  Can't open /dev/pmem0.22 exclusively.  Mounted filesystem?
E0521 10:45:10.763639       1 glog.go:119] Failed volumegroup creation: exit status 5
```

I also tried reference deployment in Direct mode, and that worked without issues.
(volumes where provisioned using healthy Region)

**Comment by okartau** [comment]
I rebooted the host and after that I was able to delete the remaining leftover namespaces.
Then I retried the LVM-mode reference deployment with namespacesize=128 i.e. with drastically reduced number of namespaces, results 2 namespaces per Region, total 4 namespaces.
The reference deployment worked without issues.
So it seems LVM-mode troubles can be avoided/reduced by avoiding big number of namespaces.
As next step, I will try with applied changes of #277

**Comment by okartau** [comment]
Tried with changes of #277, overall pretty good, deployment works in LVM mode, but there are 3 LVs created as one had "no such file" issue.
Should we perhaps introduce some retry/wait loop after LV creation to see if the device appears with slight delay, and fail only after that?

**Comment by okartau** [comment]
One more scenario discovered that creates driver confusion and leaves unclean state behind:
Reference deployment with 2 volumes with increased sizes (like 2x 160 GB). Note that one volume has eraseafter=true, means there will be `shred -n 1 /dev/DEVICE` upon deletion.
- Create pvcs, then delete pvcs (this triggers flush and shred).
- shred will run for multiple minutes.
- Without waiting for shred to end, create 2x pvc again using same deployment file.

As we have locking around Create, creation calls stop at lock-acquire, which causes Kubernetes to repeat those, producing 20 (10 of each pvc) waiting calls.
After few minutes shred exits, all those calls run in order, and 2 pvc get to Bound state.
-  delete pvc. On deletion, there are few errors "Volume not created by this driver"
which is sign bookkeeping has been messed up about which volumes exist.
After deletion, there are 4 leftover LV volumes, another sign of same.

This case demonstrates driver does not withstand repeated Creation calls that get blocked by global  lock.
We should consider making locking more granular than device lock. That global lock was added (by me) in "just in case" style without thinking about scenarios where lock remains held for longer time. We used to test on small volumes only back then.
One volume erase does not need global lock, it could work with volume-level lock to avoid double erase of same volume. Also, we can consider changing create/delete locks to be volume-group level in LVM-case, instead of global. I will try those ideas.

**Comment by okartau** [comment]
The "long shred blocking" issue described in previous comment is worked around via mutex locking change added as separate commit under #277. With change of #277 applied, the scenario delete-big-pvc (starts long shred), recreate at once gets handled sensibly: there are creation failures "no region has size" while shred is ongoing. But k8s keeps retrying creation, and after shred finishes and size becomes available, the next pvc gets created and reaches Bound state. The state remains consistent.

**Comment by pohly** [comment]
In https://github.com/intel/pmem-CSI/issues/289#issuecomment-495524038 you described a certain scenario where the current code fails. Does it only fail on real hardware or also on emulated hardware?

Either way, we should have an automated test which triggers this problem. Otherwise we can't verify (or at least not easily) that your proposed fix really works and, more importantly, we can't be sure that it continues to work when we make future changes.

**Comment by okartau** [comment]
> Does it only fail on real hardware or also on emulated hardware?

Emulated HW is smaller (32GB emulated vs. 160GB I used on HW), so failure rate/probability is likely lower, but it's fair to expect similar failures. I will try.

> we should have an automated test which triggers this problem

This particular case is easy to program using sequence of kubectl commands, I can create this.
Should we store,collect such test cases in repository? From one side, it is appealing to add such case(s) to bigger test suite , like e2e. But OTOH, checking output and debugging using e2e output is not so pleasant task, so in that sense I would prefer single-shot approach with short output. Then again, an automated run and CI style needs a "run all" approach anyway with sensible results presenting method.

**Comment by pohly** [comment]
Doing automated tests with shell scripts would need a whole lot of scaffolding to run the tests and get their results included in the overall test run. I also don't believe that debugging a failing test that is written in Go and part of the E2E test suite is harder. I would argue the opposite:
- you can single-step through the operations in a debugger
- the output of all sidecars is already captured automatically
- parallelism and complex flows are easier to implement than in shell code

I understand that there is some learning required before doing all this, but it should be worthwhile.
