### ISSUE TITLE
Repeated test_e2e leaves few leftover LV volumes or namespaces

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#292]
This issue is spin-off from #280, as it appears that both LVM and direct mode testing may leave few leftover volumes (namespaces in direct mode), which is thus independent of devicemanager mode and has to have different root cause than LVM-specific issues in #280.

20 x make_e2e on a VM cluster now shows leftover counts
(tested including fixes from #277 to avoid other LVM-mode errors):
LVM mode:
host-1: 0 volumes
host-2: 1 volumes
host-3: 4 volumes

Direct mode:
host-1: 1 namespace
host-2: 4 namespaces
host-3: 0 namespaces

note that numbers are same but on different nodes: coincidence?

**Comment by okartau** [comment]
I made another, longer test to see how that affects leftover counts
40 x make_e2e on a VM cluster, Direct mode:
host-1: 0 namespace
host-2: 5 namespaces
host-3: 0 namespaces

**Comment by avalluri** [comment]
@okartau Is it still valid, At least in my testing(LVM mode) I couldn't see any leftovers.

**Comment by okartau** [comment]
even in repeated case? If no leftovers, that's good news. I will also try my repeating script on a newest code.

**Comment by okartau** [comment]
I re-ran 50x e2e using code at 304ddf1 (few commits behind HEAD ATM).
All 50 rounds reported clean result, thats good.
But one of the nodes (node-3) had 5 leftover 4MB LVolumes after tests, means this issue is still present.

**Comment by okartau** [comment]
I looked closer into another case with 5 leftovers, and it seems like result of unsaved volumeIDs by csi-test, an issue fixed by https://github.com/kubernetes-csi/csi-test/commit/77fc8ead70f29350ded105740167e350a378c80c#diff-2b1cb03560eb8471333baa9da46fe6cd

We currently use csi-test v2.0.0 without that fix, and v2.0.1 with that fix comes by #196, so at least cases with 5 leftovers should get eliminated then.
Let's keep this open for possible other cases.

**Comment by okartau** [comment]
I haven't seen leftovers when changes of #336 are applied, thus closing.
