### ISSUE TITLE
make build-image fails on Ubuntu 18.04.2 LTS with go1.12.5 and docker 18.06.2-ce

### ISSUE THREAD

**Issue by mcastelino** [intel/pmem-CSI#293]
# make build-image failure

```
checking for pkg-config... /usr/sbin/pkg-config
checking pkg-config is at least version 0.9.0... /usr/sbin/pkg-config: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory
no
checking for libkmod... no
configure: error: in `/ndctl':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables KMOD_CFLAGS
and KMOD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
The command '/bin/sh -c ./configure ${NDCTL_CONFIGFLAGS}' returned a non-zero code: 1
Makefile:80: recipe for target 'build-image' failed
make: *** [build-image] Error 1
```

# Environment

## Kernel

```
5.0.11-050011-generic
```

## OS

```
Ubuntu 18.04.2 LTS
```

## Docker

```
Server Version: 18.06.2-ce
Storage Driver: devicemapper
```

**Comment by pohly** [comment]
Please try with the latest "devel" branch. We only had "build-image" as target for a while and went back to building multiple images. As an aside, even if we only build one, we should stick to "make build-images" instead of going back and forth.

Another change that you might not have is that switch to Clear Linux as base in the Dockerfile.

But having said that, I am confused that you are getting this error. The build should run entirely inside the Docker container and thus it shouldn't matter what you have on the host system. `make build` builds on the host, but that's not what's failing here.

**Comment by mcastelino** [comment]
@pohly it used to work before. In fact it worked yesterday on a different machine. So it could be that clearlinux base image or bundle contents have changed. Let me see if we need to add another bundle to the Dockerfile.

**Comment by pohly** [comment]
I was building today and it worked for me. Which revision of pmem-csi are you using?

**Comment by pohly** [comment]
Just to be sure I tried again, with success:
```
Step 7/34 : RUN swupd update && swupd bundle-add ${NDCTL_BUILD_DEPS} go-basic-dev && rm -rf /var/lib/swupd
 ---> Running in df1ddd1ea4a0
Update started.
Preparing to update from 29280 to 29690
Downloading packs...
...
 ---> Running in bb435ed46709
Removing intermediate container bb435ed46709
 ---> aaa3f4f7f76d
Successfully built aaa3f4f7f76d
Successfully tagged localhost:5000/pmem-csi-driver-test:canary
```

This with current "devel" = 0d0f7f8e2823b2149d39802df316e783e30c1c11.

**Comment by okartau** [comment]
I tried to build as well, and it works on a Ubuntu 18.04.2 host.
I see similar version indication by line `Preparing to update from 29280 to 29690` in output

The section where your `configure` hits trouble, looks OK in my build:
```
checking for pkg-config... /usr/sbin/pkg-config
checking pkg-config is at least version 0.9.0... yes
```

I tried to verify it's not by cached good state by pruning all docker caches, works after that as well.
Was there some problem with base image that got fixed soon after?
Can you still see the same problem?
