### ISSUE TITLE
make start: csi-node fails to come up due to incorrect registry

### ISSUE THREAD

**Issue by mcastelino** [intel/pmem-CSI#296]
# make start: csi-node fails to come up due to incorrect registry

```
pmem-csi-controller-0         2/3     ImagePullBackOff        0          14m
pmem-csi-node-48prh           0/2     Init:ImagePullBackOff   0          14m
pmem-csi-node-62ppm           0/2     Init:ImagePullBackOff   0          14m
pmem-csi-node-kh7qf           0/2     Init:ImagePullBackOff   0          14m
```

due to

```
  Type     Reason            Age                    From                                  Message
  ----     ------            ----                   ----                                  -------
  Normal   Scheduled         6m34s                  default-scheduler                     Successfully assigned default/pmem-csi-node-48prh to pmem-csi-clear-govm-worker1
  Normal   Pulling           5m53s (x3 over 6m33s)  kubelet, pmem-csi-clear-govm-worker1  Pulling image "172.17.0.1:5000/pmem-csi-driver-test:canary"
  Warning  Failed            5m53s (x3 over 6m31s)  kubelet, pmem-csi-clear-govm-worker1  Failed to pull image "172.17.0.1:5000/pmem-csi-driver-test:canary": rpc error: code = Unknown desc = Error response from daemon: manifest for 172.17.0.1:5000/pmem-csi-driver-test:canary not found
  Warning  Failed            5m53s (x3 over 6m31s)  kubelet, pmem-csi-clear-govm-worker1  Error: ErrImagePull
```

I am running a registry on the host machine

```
d4bf2618d1a6        registry:2                 "/entrypoint.sh /etc…"   33 minutes ago      Up 33 minutes       0.0.0.0:5000->5000/tcp   registry
```

We may be missing some documentation on customizing the yaml to pick up the local registries in the case of `make start`

**Comment by mcastelino** [comment]
I tried the following without success

```
 TEST_CHECK_SIGNED_FILES=0 TEST_CREATE_REGISTRY=1 TEST_LOCAL_REGISTRY=1 TEST_PMEM_REGISTRY=1 make -d start
```

**Comment by okartau** [comment]
> I do not see a corresponding push for `localhost:5000/pmem-csi-driver-test:canary`

You need `make push-images` to make and push both regular and test images.
It seems describing that target has been (unintentionally?) skipped in README.
Getting ideas of different make targets may need a look into Makefile (and possibly it's includes).
In some earlier PR thread I proposed idea documenting make targets separately, like via `make help`, but it has not been done, or is it considered complex and over-engineering (as it would add another area requiring maintenance for consistency).

**Comment by pohly** [comment]
Manohar Castelino <notifications@github.com> writes:
> We may be missing some documentation on customizing the yaml to pick
> up the local registries in the case of `make start`

Currently this is documented in
https://github.com/intel/pmem-CSI/blob/devel/test/test-config.sh and
https://github.com/intel/pmem-CSI/blob/devel/README.md#configuring-multiple-clusters
links to it.

But indeed, when following just the steps in
https://github.com/intel/pmem-CSI/blob/devel/README.md#qemu-and-kubernetes
from top to bottom, one misses "make push-images". I'll send a PR.

**Comment by pohly** [comment]
@mcastelino does https://github.com/intel/pmem-CSI/pull/298 address this?

**Comment by mcastelino** [comment]
> @mcastelino does #298 address this?

@pohly yes it does and helps the user quickstart from the main documentation. 
I now how the base cluster up and running based off the main docs. Thank you!
