### ISSUE TITLE
"capacity restored" test fails

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#322]
After merging PR #196, the following test of the "devel" branch failed:
```
[Fail] sanity pmem csi [AfterEach] capacity is restored after controller restart 
/go/src/github.com/intel/pmem-csi/test/e2e/storage/sanity.go:109
```

https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-CSI/detail/devel/8/pipeline

**Comment by avalluri** [comment]
#324 Is supposed to fix these type of test failures, caused by delay in the re-registering of Nodes on Controller restarts.

**Comment by pohly** [comment]
Amarnath Valluri <notifications@github.com> writes:
> #324 Is supposed to fix these type of test failures, caused by delay
> in the re-registering of Nodes on Controller restarts.

That PR may shorten the delay, but the race condition remains.

**Comment by avalluri** [comment]
#324 Has the needed fix and it's merged.
