### ISSUE TITLE
controller: ignores errors when deleting volumes

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#329]
Found in https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/PR-327/runs/1/nodes/59/log/?start=0 (part of issue #319):
```
pmem-csi-controller-0/pmem-driver: W0704 08:18:22.409906       1 glog.go:99] Failed to delete volume 3bdf2d3e-9e34-11e9-88d0-ce52ad0608ec on pmem-csi-clear-1-14-direct-worker1: rpc error: code = DeadlineExceeded desc = context deadline exceeded
pmem-csi-controller-0/pmem-driver: I0704 08:18:22.409958       1 glog.go:58] DeleteVolume: volume 3bdf2d3e-9e34-11e9-88d0-ce52ad0608ec deleted
```

Does that mean that the gRCP errors was ignored and the controller continues by assuming that the volume was deleted?

**Comment by pohly** [comment]
Yes, the code merely logs errors as warnings:
https://github.com/intel/pmem-csi/blob/2e59826b538e3358e8bd132881298ed53b68e328/pkg/pmem-csi-driver/controllerserver-master.go#L287-L302

That's not how Kubernetes works. When there is an error, some retry loop must repeat the same operation until eventually it succeeds or a human admin intervenes. An automated system cannot fail and then expect an admin to clean up manually, that simply doesn't scale.

The retry loop in this case is in the external-provisioner. The code must be changed to return an error to the provisioner.

**Comment by pohly** [comment]
Do we have other cases where errors are merely logged as warnings?

**Comment by avalluri** [comment]
> Yes, the code merely logs errors as warnings:

If I remember correctly, this was because of Cache volumes, How to deal if the volume is deleted on some nodes, but other nodes reported error.

But we can fix this, by reporting the first error and make sure that Nodes handle repeated delete calls without reporting an error. Expecting that external-provisioner maintains the retry loop.

**Comment by pohly** [comment]
> make sure that Nodes handle repeated delete calls without reporting an error

They should already do that. Idempotent calls are an important part of a distributed system because a response to a request might get lost and callers simply have to retry the same operation.
