### ISSUE TITLE
Volume deletion code path should block calling ClearDevice,shred for volume that is in use

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#338]
Recent cases like #317 #337 have indicated there is code path where a volume that remained mounted, gets erased by shred. This has happened for various reasons, few cases been caused by incorrect paths use by tester code. The reason does not matter so much: if the code can take the path, we should handle it in less-damaging way, avoiding destruction of live file system.

On a call path: DeleteVolume-ClearDevice we should detect that the corresponding file system is in use, and return error **before** calling ClearDevice and shred.
Current code returns error anyway just one step later in lvremove, so shred of device is unnecessary destruction.
This analysis is based on LVM mode where most of recent cases have been debugged, but likely is equally relevant in direct mode as well.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> This has happened for various reasons, few cases been caused by
> incorrect paths use by tester code. The reason does not matter so
> much: if the code can take the path, we should handle it in
> less-damaging way, avoiding destruction of live file system.

It's good if the driver has sanity checks against a malfunctioning CO,
but ultimately it's still the COs (or in this case, the test code which
pretends to be the CO) which must behave correctly.
