### ISSUE TITLE
volume size rounding

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#348]
The driver should:
- do rounding only in the layer (LVM or ndctl) which actually knows about size limitations
- only ever round up, not down: the request is to provide at least the specified amount of storage
- report back the actual size in `CreateVolumeResponse` to ensure that the result is visible in Kubernetes (stored in the PV)

Right now rounding done downwards (issue #119) and fails in some configurations when the size is 0. The actual size is not reported.

**Comment by okartau** [comment]
Reporting the size back from CreateVolume is not so straightforward to achieve, as create call does not return context about created element. There is just one way to read back sizes, it's ListDevices() that return names, device-paths, sizes of all volumes. To accomplish what is asked here, we have to call ListDevices after successful creation in CreateVolume, and pick the volume info for volume we just created, and use the actual size in response. Makes sense to put actual size into volumes registry there as well (currently the asked value goes there).

**Comment by okartau** [comment]
> Makes sense to put actual size into volumes registry

This we should re-check separately for both Direct and LVM mode.
I think in both cases there is separate code, and we keep the asked size in registry, not real size

**Comment by pohly** [comment]
Just introduce a new cs.dm.RoundVolumeSize() call and used that instead of the current code here:
https://github.com/intel/pmem-csi/blob/b59de7d0431719d1af762256d12caef24da7ac5b/pkg/pmem-csi-driver/controllerserver-node.go#L177-L182

**Comment by okartau** [comment]
it's not that straightforward. 
DeviceManager for LVM can hard-code this to some sane value like 4 MB.
DeviceManager for ndctl does not (in current code) know/maintain the correct alignment. 
And making it to know is not that simple, as this value is region-dependent, (at least in theory) can differ per region, and DeviceManager layer does not keep context for regions. Current implementation fetches this value from Region context during Volume Creation, and size is aligned there on the fly, this happens in ndctl package which is layer below Device Manager.

**Comment by okartau** [comment]
I have proposla to solve this: The pointed code (forcing size to 4MB) actually is irrelevant in Direct mode where alignment up is forced to smaller values. It only becomes relevant for LVM mode as explained in comment. So we can still do as you propose, return some another sane default in ndctl Manager (like 1GB) and let the actual creation do the rest of alignment.

**Comment by okartau** [comment]
Another way: delete the pointed code, and add forced set to 4MB (if smaller) in LVM Devicemanager
(i.e. in essence move that code from there into LVM Manager)

**Comment by okartau** [comment]
> report back the actual size in `CreateVolumeResponse`

With that happening (https://github.com/intel/pmem-csi/pull/349/commits/a1b89f5740c55156c6c88313c3c7c09bc425cebd), a test started to fail:
```
supports cache volumes [It]
  go/src/github.com/intel/pmem-csi/test/e2e/storage/sanity.go:418
      additional volume size on node #1(dns:///172.17.0.3:9735)
      Expected
          <int64>: 37748736
      to equal
          <int64>: 34603008
```
Where bigger value is the real allocation size that was fixed into volume registry and also went into CreateResponse, and smaller value is size in original request.
Does the tester still use size in request and not size in response?
I think the size replacing code works (you are welcome to review mentioned commit), however there is no log of CreateVolumeResponse commit so we  have no hard evidence in logs what we report back.

There is another error with two sizes which seems to have similar pattern:
"same volumes as before node reboot"

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:

>> report back the actual size in `CreateVolumeResponse`
>
> With that happening (https://github.com/intel/pmem-csi/pull/349/commits/a1b89f5740c55156c6c88313c3c7c09bc425cebd), a test started to fail:
> ```
> supports cache volumes [It]
>   go/src/github.com/intel/pmem-csi/test/e2e/storage/sanity.go:418
>       additional volume size on node #1(dns:///172.17.0.3:9735)
>       Expected
>           <int64>: 37748736
>       to equal
>           <int64>: 34603008
> ```
> Where bigger value is the real allocation size that was fixed into volume registry and also went into CreateResponse, and smaller value is size in original request.
> Does the tester still use size in request and not size in response?

The test was written under the assumption that the volume is created
exactly with the chosen size. That assumption no longer holds and the
test needs to be updated accordingly: either use a volume size that
doesn't need rounding, or relax the check.

> I think the size replacing code works (you are welcome to review
> mentioned commit), however there is no log of CreateVolumeResponse
> commit so we have no hard evidence in logs what we report back.

The pod logging can be incomplete because it collects output
asynchronously: when a test completes and the testsuite shuts down, some
output might not have been collected yet.

**Comment by okartau** [comment]
The 'report back the actual size' part of this issue request appears to need multiple changes (some of which are non-trivial) in both driver and tester code that it is safer not attempt this now, but postpone to become a separate change activity.
We thus limit current change in #349 to be about alignment and rounding changes.
