### ISSUE TITLE
"Connecting to" log msg always doubled

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#356]
Every time controller connects to a node for GRPC, we log two lines:
```
pmem-csi-controller-0 Connecting to node controller : tcp://172.17.0.4:10001
pmem-csi-controller-0 Connecting to 172.17.0.4:10001
```
2nd of those shows completely redundant information and can be avoided.
In a typical e2e test this produces thousands of lines which don't add value.

**Comment by okartau** [comment]
Both log messages are give at level 3.
Simplest solution is just to drop log line from Connect:
```
+++ b/pkg/pmem-grpc/grpc.go
@@ -29,7 +29,6 @@ func Connect(endpoint string, tlsConfig *tls.Config) (*grpc.ClientConn, error) {
        if err != nil {
                return nil, err
        }
-       glog.V(3).Infof("Connecting to %s", address)
        dialOptions := []grpc.DialOption{grpc.WithBackoffMaxDelay(time.Second)}
```

There are 2 callers currently (aside from unit test call) logging message using explanation where they connect. This is useful information.
To make the fix more correct, we could keep the log inside Connect() and delete outer calls,
that would guarantee all other (future added) callers also get logging automatically.
But then we would throw away those useful texts "to node controller" and "to registry server",
so what about adding another parameter "dest string" to Connect(), log using this inside Connect, and delete the log lines (2 occasions) before calling Connect.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> But then we would throw away those useful texts "to node controller" and "to registry server",
> so what about adding another parameter "dest string" to Connect(), log
> using this inside Connect, and delete the log lines (2 occasions)
> before calling Connect.

Let's not add parameters that are only useful for creating better log
messages. The right solution for this is to pass a context and in that
context have a logger that the function is meant to use. Then with
structured logging, the caller can extend the logging in all invoked
functions with additional contextual information, for example the
request that is currently being processed or (in this case) what it is
that is supposed to be connected to.

**Comment by okartau** [comment]
This is nice plan, but isn't that quite close to what you plan to avoid: "added parameter (i.e. context) only useful for creating better log". And this variant comes with more source lines.
Passing context would make sense if that context is useful overall, but here we only add it for better logging?

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> Passing context would make sense if that context is useful overall,
> but here we only add it for better logging?

A context parameter is also useful to carry additional information, like
a deadline for the operation.
