### ISSUE TITLE
File system too small for VolumeIO test suite in LVM mode

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#368]
As part of enabling more test suites, I try VolumeIO next. This seems overall useful, creating files of various sizes and checking the sizes and contents.
The test set is another one (in addition to VolumeMode tests) depending on local kubectl, so it needs similar re-work as we have sketched out in #365.
But if tried with local kubectl present, it already exposes a test setup problem we will hit:
The test attempts this sequence:
1. create 1 MB "dd_if" file as source for dd (this is created by pod init, not part of kubectl cmds)
2. create 1 MB test file , dd-ing from source once
3. create 100 MB test file, dd-ing from source 100 times and appending.

This sequence uses 102 MB.
I added "ls -l, df" to pod commands and this is the state after step 2:
```
$ ls -l /opt
-rw-r--r--    1 root     1234       1048576 Jul 23 06:02 pmem-csi_io_test_volumeio-959-1048576
-rw-r--r--    1 root     1234       1048576 Jul 23 06:02 pmem-volumeio-959-dd_if
$ df /opt
Filesystem           1K-blocks      Used Available Use% Mounted on
                          3952      2072      1596  56% /opt
```

In that LVM-mode test system, this test is attempted on a 4MB file system, and 100MB creation fails as there is <2MB free space left.
Note that volume creation used originally 1MB request which was rounded up to 4MB by LVM mode minimal alignment req.
I haven't tried yet same on Direct mode, but I can guess there it will pass as Direct mode will create a 2GB file system as minimal.

Seems that VolumeIO test does not specify the file system size at all, but relies on some existing PV value which happens to be 1M in our case?

Another outcome to improve those tests:
100-times loop dd'ing to test file does not return error to test code, although the file system got full
and it was able to create 1843200-byte file instead of desired 104857600.
So the tester does not detect failure here:
```
kubectl exec pmem-io-client -- /bin/sh -c i=0; while [ $i -lt 100 ]; do dd if=/opt/pmem-volumeio-959-dd_if bs=1048576 >>/opt/pmem-csi_io_test_volumeio-959-104857600 2>/dev/null; let i+=1; done'
```

but only detects the size mismatch later:
```
Jul 23 09:03:28.118 FAIL: Unexpected error:
    <*errors.errorString | 0xc000883180>: {
        s: "size of file /opt/pmem-csi_io_test_volumeio-959-104857600 is 1843200, expected 104857600",
    }
```

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> Seems that VolumeIO test does not specify the file system size at all,
> but relies on some existing PV value which happens to be 1M in our
> case?

https://github.com/kubernetes/kubernetes/pull/78306 is meant to address
that, but the current solution needs further work. In the meantime we
have to increase the claim size of our driver test to be large enough
for the tests that we want to run.

> Another outcome to improve those tests:
> 100-times loop dd'ing to test file does not return error to test code, although the file system got full
> and it was able to create 1843200-byte file instead of desired 104857600.
> So the tester does not detect failure here:
> ```
> kubectl exec pmem-io-client -- /bin/sh -c i=0; while [ $i -lt 100 ]; do dd if=/opt/pmem-volumeio-959-dd_if bs=1048576 >>/opt/pmem-csi_io_test_volumeio-959-104857600 2>/dev/null; let i+=1; done'
> ```
>
> but only detects the size mismatch later:
> ```
> Jul 23 09:03:28.118 FAIL: Unexpected error:
>     <*errors.errorString | 0xc000883180>: {
>         s: "size of file /opt/pmem-csi_io_test_volumeio-959-104857600 is 1843200, expected 104857600",
>     }
> ```

Would be worth fixing upstream.

**Comment by pohly** [comment]
It's fixed already upstream.
