### ISSUE TITLE
move to '-V <version>' with swupd update

### ISSUE THREAD

**Issue by mythi** [intel/pmem-csi#379]
```-m``` parameter is deprecated and it's good to get rid of it:

```
  -m, --manifest=V        NOTE: this flag has been superseded. Please use -V instead
```

Affects: Dockerfile

**Comment by avalluri** [comment]
@mythi Where was this option used in our scripts? I could find on in comments part in Dockerfile, Is this the one you are referring to?

**Comment by mythi** [comment]
@avalluri I noticed the same after I reported this issue. This is pretty minor. `-m` is only mentioned in the comments but the update script already uses `--version`

**Comment by avalluri** [comment]
Thanks, I will fix the comments part then.
