### ISSUE TITLE
release images are not reproducible

### ISSUE THREAD

**Issue by mythi** [intel/pmem-csi#382]
We have related issues #378 and #379 but I think this deserves it's own issue.

While working on QAT image reproducible builds I discovered a problem with ``` ${SWUPD_UPDATE_ARG}```:  The value is reset before it's used. The documentation confirms this:

```
An ARG instruction goes out of scope at the end of the build stage where it was defined. To use an arg in multiple stages, each stage must include the ARG instruction.
```

This means ```swupd update``` never gets to use the locked version:

```
Step 8/42 : RUN echo "version ${SWUPD_UPDATE_ARG}" && swupd update ${SWUPD_UPDATE_ARG} && swupd bundle-add ${NDCTL_BUILD_DEPS} go-basic-dev && rm -rf /var/lib/swupd
 ---> Running in 385297cac894
version
Update started.
Preparing to update from 30650 to 30700
Downloading packs for:
```

**Comment by avalluri** [comment]
Thanks, @mythi  for finding this, So redefining `ARG SWUPD_UPDATE_ARG` in each build stage should fix the problem right? I found an interesting discussion related to this: https://github.com/moby/moby/issues/34129
