### ISSUE TITLE
kubelet repeats "RegisterPlugin error" on kubernetes 1.15 nodes

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#394]
kubelet error is repeatedly logged on all nodes system log with kubernetes 1.15 deployment:
```
kubelet[2627]: E0830  goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/pmem-csi.intel.com/csi.sock" failed. No retries permitted until 2019-08-30 08:12:56.950765334 +0000 UTC m=+535.947459351 (durationBeforeRetry 32s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/pmem-csi.intel.com/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```

This has seen on systems:
4xVM govm cluster, Ubuntu 19.04, kubernetes 1.15.3
2xbaremetal cluster, Fedora-30, kubernetes 1.15.3

This msg is **not** reported on system:
4xVM govm cluster, Clear 29820, kubernetes 1.14.2

This error does not affect functionality: deployment, e2e and sanity tests work OK.
But it may leave impression something is wrong.
We should investigate the cause, possibly find a way to avoid this error msg,
and if  unavoidable, we should document it.

**Comment by avalluri** [comment]
This is even present in v1.14:

`kubelet[10520]: E0830 09:38:47.257975   10520 plugin_watcher.go:120] error failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/pmem-csi.intel.com/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration when handling create event: "/var/lib/kubelet/plugins/pmem-csi.intel.com/csi.sock": CREATE`

But on 1.14 registration failures are not retried, whereas 1.15 introduced plugin-manager that keep retrying till all the plugin(socket files under` /var/lib/kubelet/{plugins,plugin_registry}`) registrations success.

PMEM-CSI is using `/var/lib/kubelet/plugins/` folder for keeping its listening socket, this folder is watched by plugin-manger for plugin changes. By using a different socket location(`/var/lib/kubelet/pmem-csi.intel.com`) could fix this issue.

**Comment by okartau** [comment]
Should we change socket location in our deployment files then?
Starting with 1.14 ?

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> Should we change socket location in our deployment files then?
> Starting with 1.14 ?

If that version already supported the new location, then yes.

**Comment by avalluri** [comment]
> Should we change socket location in our deployment files then?
> Starting with 1.14 ?

Yes. we should stop using deprecated path. @pohly  What would be the preferred location for driver socket path? Currently, it's using  `/var/lib/pmem-csi.intel.com`  for saving state, shall we use the same even for sockets or use new location under kubelet's state directory: `/var/lib/kubelet/pmem-csi.intel.com`

**Comment by pohly** [comment]
Amarnath Valluri <notifications@github.com> writes:
> Yes. we should stop using deprecated path. @pohly What would be the
> preferred location for driver socket path? Currently, it's using
> `/var/lib/pmem-csi.intel.com` for saving state, shall we use the same
> even for sockets

That sounds like a good idea.

**Comment by amgads** [comment]
we're seeing a similar message on 1.16
Jun 20 21:58:16 bcmt1912perfsmp-control-01 kubelet: I0620 21:58:16.432004    2347 clientconn.go:577] ClientConn switching balancer to "pick_first"
Jun 20 21:58:16 bcmt1912perfsmp-control-01 kubelet: E0620 21:58:16.434156    2347 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock" failed. No retries permitted until 2020-06-20 22:00:18.434133718 +0000 UTC m=+10506182.548066578 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
