### ISSUE TITLE
unintentional changes in release-0.5 branch

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#396]
89c51dc83054c45b6b862d88b0e56f2022596618 contains changes that shouldn't have been in 0.5.1.

We need to revert those and do a 0.5.3.

**Comment by okartau** [comment]
I mentioned "Resolves: #" in PR 1st comment but merge did not close this, why. Can be closed now?

**Comment by pohly** [comment]
> I mentioned "Resolves: #" in PR 1st comment but merge did not close this, why. Can be closed now?

Yes. GitHub probably didn't do automatically that because the commit wasn't merged into "devel" or "master".
