### ISSUE TITLE
DeleteVolume response is incorrect if volume is in use

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#402]
CSI spec says that if a volume is in use, DeleteVolume response should be error=FAILED_PRECONDITION.
Currently, PMEM-CSI responds with codes.InternalError in all cases when lower layer (Device) returns any error, although the BUSY status is detected and is one of the reasons to fail.
To make the GRPC error correct, we have to start returning more detailed error codes by cs.dm.DeleteDevice and form a RPC return code correctly if volume/device was in-use.

**Comment by okartau** [comment]
The fact that current PMEM-CSI code passed e2e and sanity tests, is a sign that this scenario is not tested.

**Comment by okartau** [comment]
Changes of #420 fixed that, it seems, @avalluri do you agree? Now NodeController returns FailedPrecondition if volume is in use.
In that case, I think we can close this issue.

**Comment by avalluri** [comment]
> Changes of #420 fixed that, it seems, @avalluri do you agree? Now NodeController returns FailedPrecondition if volume is in use.
> In that case, I think we can close this issue.

Yes, we can close this.
