### ISSUE TITLE
device path changes during reboot

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#467]
@okartau observed that block device names change during reboot (https://github.com/intel/pmem-csi/pull/449#issuecomment-550273329).

This raised the question whether the state saving code deals with this correctly. Do we have a test for it?

@avalluri, do you know?

**Comment by avalluri** [comment]
We are not saving Device names/paths into the state. The information we save in the state is: `VoumneId, Size & Params`. So underlined device paths shouldn't affect us.

**Comment by okartau** [comment]
Then we should not have problems with changing name.
I leftover tester code, I removed device name fields from comparison so these will not affect the check.
