### ISSUE TITLE
direct mode: volumes not removed completely

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#472]
When creating and deleting a volume in direct mode, it's namespace remains in "inactive" state. In that state it is found by  pmemNdctl.getDevice from pkg/pmem-device-manager/pmd-ndctl.go, which prevents creating another volume with that name.

I'm not sure what to expect here: should the namespace be gone completely? Or should it be ignored and overwritten when the name is used again?

To reproduce:
- run the pkg/pmem-device-manager test from https://github.com/intel/pmem-csi/pull/420 multiple times on the same host in direct mode
or
- `kubectl create -f deploy/common/pmem-pvc.yaml`
- `kubectl delete -f deploy/common/pmem-pvc.yaml`
- `for i in 1 2 2; do echo $i; _work/pmem-govm/ssh.$i sudo ndctl list --idle; done`

->

```
1
[
  {
    "dev":"namespace0.0",
    "mode":"raw",
    "size":0,
    "uuid":"00000000-0000-0000-0000-000000000000",
    "sector_size":512,
    "state":"disabled"
  }
]
2
[
  {
    "dev":"namespace0.1",
    "mode":"raw",
    "size":0,
    "uuid":"00000000-0000-0000-0000-000000000000",
    "sector_size":512,
    "state":"disabled"
  },
  {
    "dev":"namespace0.0",
    "mode":"raw",
    "size":0,
    "uuid":"00000000-0000-0000-0000-000000000000",
    "sector_size":512,
    "state":"disabled",
    "name":"test-dev"
  }
]
3
[
  {
    "dev":"namespace0.2",
    "mode":"raw",
    "size":0,
    "uuid":"00000000-0000-0000-0000-000000000000",
    "sector_size":512,
    "state":"disabled"
  },
  {
    "dev":"namespace0.0",
    "mode":"raw",
    "size":0,
    "uuid":"00000000-0000-0000-0000-000000000000",
    "sector_size":512,
    "state":"disabled",
    "name":"88e0e66821229cbc2079a486ac77cf0e33a2f655"
  }
]
```

While the two example volumes were active, they were listed as:
```
3
[
  {
    "dev":"namespace0.2",
    "mode":"raw",
    "size":0,
    "uuid":"00000000-0000-0000-0000-000000000000",
    "sector_size":512,
    "state":"disabled"
  },
  {
    "dev":"namespace0.1",
    "mode":"fsdax",
    "map":"dev",
    "size":4294967296,
    "uuid":"c05515e8-0ba3-11ea-b052-0242ac110005",
    "sector_size":512,
    "align":1073741824,
    "blockdev":"pmem0.1",
    "name":"83704ecc919dfe1f22f8600440f79b5bfdfa2a19"
  },
  {
    "dev":"namespace0.0",
    "mode":"fsdax",
    "map":"dev",
    "size":4294967296,
    "uuid":"c043a939-0ba3-11ea-b052-0242ac110005",
    "sector_size":512,
    "align":1073741824,
    "blockdev":"pmem0",
    "name":"88e0e66821229cbc2079a486ac77cf0e33a2f655"
  }
]
```

Note that only one remains behind as inactive.

**Comment by okartau** [comment]
I recall having seen explanation about ndctl internals that namespace deletion involves marking namespaces disabled. So a deleted namespace (or part of its metadata) may exist in disabled mode, and ndctl display code has to deal with that so that user-visible state remains as expected. There is also notion of "seed" namespace which remains not deleted even if others are gone. We may see some of such side-effects here.

**Comment by pohly** [comment]
So it's a bug in `pmemNdctl.getDevice` that it doesn't filter out the disabled namespace.

**Comment by avalluri** [comment]
> I'm not sure what to expect here: should the namespace be gone completely? Or should it be ignored and overwritten when the name is used again?

Yes, we should ignore inactive namesapaces: [This change](https://github.com/intel/pmem-csi/pull/420/commits/8feea9f65f629b85700b7580f3c4b36b616564bd) fixes the issue.
