### ISSUE TITLE
Follow-up improvement of NodeStage handling of mount flags

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#483]
There was something left for follow-up work from #463:
@avalluri wrote:
-  current code is not considering the mount flags in stage volume for repeated mounts.
- I feel instead of caching mount flags, we should retrieve that information from the existing mount point as we are doing that from `fsType`.  We should change our logic of determining the existing filesystem of a mount path. Currently, we are retrieving that information using`file` and `blkid`. Instead, if we can retrieve both mount flags and fstype from procfs.

**Comment by pohly** [comment]
The current code also isn't thread-safe and crash-resistent: https://github.com/intel/pmem-csi/issues/502

**Comment by pohly** [comment]
@avalluri was this resolved by your PR https://github.com/intel/pmem-csi/pull/673?

**Comment by avalluri** [comment]
We could close this. As @pohly pointed #673 covers this.
