### ISSUE TITLE
TEST_DEPLOYMENTMODE check in test.make not working properly

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#492]
That line in test.make seems to have a problem:
`echo PMEM_CSI_IMAGE=$$TEST_LOCAL_REGISTRY/pmem-csi-driver$$(if $$TEST_DEPLOYMENTMODE = testing; then echo -test; fi):$(IMAGE_VERSION); \`

In test log:
`[2019-12-11T21:33:28.259Z] bash: testing: command not found`

as result, value of image will be;
`PMEM_CSI_IMAGE=172.17.0.1:5000/pmem-csi-driver:canary`

which is not desired since TEST_DEPLOYMENTMODE was "testing"

I think the `if` check needs to have `[]` around:
`if [ $$TEST_DEPLOYMENTMODE = testing ]`

However, this did not lead to tester error, does regular container and -test container behave same way in this context?

**Comment by pohly** [comment]
They both work, which is why this wasn't found earlier. I already fixed it while working on https://github.com/intel/pmem-csi/pull/487 (see https://github.com/intel/pmem-csi/pull/487/commits/0831ccf816dfb706f0165670410218331ba10281).

**Comment by okartau** [comment]
Closing, fix was re-merged
