### ISSUE TITLE
Document (optionally: make closer to k8s convention) use of log levels

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#497]
Discussion under #495 brought up a point we do not document use of log levels.
We could add note in README (or better DEVELOPMENT ?) about our style, which seems to be off-by-one from guidelines at https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
i.e. we use (Info levels) 3 for production level and 4,5 for extended/development.
I recall the history was, when we cleaned our logging levels, we had most of statements at level 3 already so we wanted to keep those and we used 4 and 5 as more verbose levels.
We do not use info levels 0,1,2 currently at all.
At some point, do we wish to change all levels so that we conform better to convention in above mentioned page?

**Comment by pohly** [comment]
In addition, we should switch to structured logging similar to this KEP: https://github.com/kubernetes/enhancements/pull/1367

@grahamwhaley also pointed out some cases where the code currently uses `Infof` without actually needing formatting.

**Comment by okartau** [comment]
I started #528 replacing Infof to Info, that takes care of klog-using part.
But what do you propose to use instead of framework.Logf and framework.Failf ?

**Comment by grahamwhaley** [comment]
@okartau - thanks for that. Indeed, it looks like the framework [does not give you the option](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/log/logger.go) - so I guess, not much to be done there :-)
