### ISSUE TITLE
volInfo: mutex locking, persist across restarts

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#502]
Looking at https://github.com/intel/pmem-csi/blob/fbaa784d853c063236d039dcd73aa356135b3cc4/pkg/pmem-csi-driver/nodeserver.go#L54 and how ns.volInfo is used I have two observations:

- It gets accessed in read/write mode from potentially parallel gRPC calls for different volumes. I think mutex locking for it is missing.
- It doesn't get stored on disk. I suspect that means that https://github.com/intel/pmem-csi/blob/fbaa784d853c063236d039dcd73aa356135b3cc4/pkg/pmem-csi-driver/nodeserver.go#L222-L233 will not work correctly after a node service restart or node reboot.

**Comment by pohly** [comment]
@okartau you wrote that code. Do you want to fix it or shall we find someone else for it?

**Comment by avalluri** [comment]
> * It doesn't get stored on disk. I suspect that means that
>    will not work correctly after a node service restart or node reboot.
AFIK, Those checks are only for detecting multiple PublishVolume() calls of a volume on node, which does not affect by node reboots.

**Comment by pohly** [comment]
> AFIK, Those checks are only for detecting multiple PublishVolume() calls of a volume on node, which does not affect by node reboots.

Please replace "node reboot" with "pod restart", then we still have a problem.
