### ISSUE TITLE
handle volume ID hash conflicts

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#503]
https://github.com/intel/pmem-csi/blob/fbaa784d853c063236d039dcd73aa356135b3cc4/pkg/pmem-csi-driver/controllerserver-node.go#L172-L179 creates a new volume ID from the `CreateVolumeRequest.Name`.

While unlikely, it is possible that two different names hash to the same ID. We should either catch that and throw an error (just to be safe) or add a comment why ignoring this potential conflict is fine.

**Comment by pohly** [comment]
Same code exists in master controller: https://github.com/intel/pmem-csi/blob/fbaa784d853c063236d039dcd73aa356135b3cc4/pkg/pmem-csi-driver/controllerserver-master.go#L171-L176

This should be moved into a common utility function.

**Comment by pohly** [comment]
We also should add a comment explaining *why* this hashing is done instead of just using the `Name` string.

**Comment by okartau** [comment]
> We should either catch that and throw an error (just to be safe) or add a comment why ignoring this potential conflict is fine.

What if we try to handle it in 3rd way: trying to continue without error?
We don't have requirement that VolumeID has to be hash of name, it is up to driver to generate some unique ID. And we dont have other code path generating hash where we must get same value. So, what about this: We generate hash and see did we get unique VolumeID. If not, we try again, for example by getting new hash from Name2+hash. (if we get collision again, it is already much-much smaller chance, but we can continue that loop until we get unique hash). Then we return new hash as VolumeID. Would such method work? The resulting VolumeID will be repeatable if the set of existing VolumeNames/VolumeIDs remains, but I think the main point is, we dont even need it to be repeatable as no other code path generates VolumeIDs.
There is however similar hash generation in node part of code, that may complicate things for this scenario.

**Comment by pohly** [comment]
> The resulting VolumeID will be repeatable if the set of existing VolumeNames/VolumeIDs remains, but I think the main point is, we dont even need it to be repeatable as no other code path generates VolumeIDs.

The "if the set of existing VolumeNames/VolumeIDs remains" part is crucial here. We can't assume that, so with this proposal we may end up creating different volume IDs for the same volume name.

Is that a problem? Looking at the code I suspect that it wouldn't be a problem. Idempotency uses the volume name to find some already existing volume.

But why use hashing at all? Wouldn't it be simpler to just generate a UUID? We can assume that UUIDs are random enough that we don't get the same one twice, so we don't need to check for conflicts. I'd also like to bring up the idea again of inserting parts of the volume name into the volume ID, to make it more readable...

The probability of hash conflicts is also low. The difference is that the volume name is under control of a user, so not checking for conflicts opens the door for a (denial-of-service?) attack where the user intentionally chooses a name that has the same hash as an existing volume.

**Comment by okartau** [comment]
> But why use hashing at all? Wouldn't it be simpler to just generate a UUID?

True. The logic in my thinking "let's generate something until unique" actually is same as in generating new VolumeID from very start, leaving out the part using Name as seed.

> we don't need to check for conflicts

If we care enough to think about hash collision, we should also consider the chance of UUID collision exists. But handling this is simple, generate a new. And this is different/easier than hash collision in sense that attacker can not cause collision using pre-crafted Name.

> to bring up the idea again of inserting parts of the volume name into the volume ID

yes I also like the idea but can we find a method to do this which satisfies all constraints, and does not depend on already existing names and IDs?
The most elegant (and also user-readability-friendly) way would be to use Name directly. But that we can't do, at least in LVM case, for 2 reasons: 1) CSI allows longer names than LVM, 2) CSI allows characters in Name that are not allowed in LVM names. And it's not trivial to pick a part of name, as we don't know which part(s) of name may overlap with existing names.
Inserting any logic that depends on checking existing names is probably not good idea (other than checking entire name  match of course).

**Comment by okartau** [comment]
What about this idea:
We pick first N chars from Name, and add generated new UUID.
Pros: 
* we keep some information from name, which helps if that part is unique
* we usually get unique Volume ID with 1st try

Cons:
* if Names use common prefix with len > N, then all those parts will look same and idea does not serve the purpose
* If Name prefixes match, _and_ there is also UUID collision, this would be a replica VolumeID. We can get over it by generating new UUIDs until we get a unique one. This is added, not-so-elegant complexity in code, needs checking of existing VolumeIDs.

**Comment by pohly** [comment]
> If we care enough to think about hash collision, we should also consider the chance of UUID collision exists.

I care about hash collisions because of the potential attack vector. I care a lot less about UUID conflicts because those should be unlikely with good pseudo-random numbers. So this is not directly comparable.

If we can check for UUID conflicts without too much extra effort and complexity, then let's do it.

> We pick first N chars from Name, and add generated new UUID.

Yes, looks good to me. If we put this into an utility library we can also tweak the actual implementation later. We just need to define precisely what the limitations for the volume ID are, in particular the maximum length. Right now I am not aware of any documentation or comments regarding that in the repo.

**Comment by okartau** [comment]
> Right now I am not aware of any documentation or comments regarding that in the repo.

LVM-mode volume name size limitation was described in this comment: https://github.com/intel/pmem-csi/issues/404#issuecomment-531281699
Should we write it down in DEVELOPMENT?
There is also char-set limitation which I think is not described yet in this repo.

Let's also note that we had UUID-generated VolumeIDs before hash-based approach. See the pointed comment described how transition from generated UUID to hash was to solve the issue where multiple LVM volumes were incorrectly created in repeated calls based on single Name, because generated VolumeID made those look as different devices for underlying device layer. We need to be careful now in move back to UUID-based approach, not to recreate problem(s) of that type.

**Comment by pohly** [comment]
> Should we write it down in DEVELOPMENT?

I would put it into a comment for the "volume name to volume ID" helper function and/or define constants for the string lengths if those are of use somewhere.

> Let's also note that we had UUID-generated VolumeIDs before hash-based approach. See the pointed comment described how transition from generated UUID to hash was to solve the issue where multiple LVM volumes were incorrectly created in repeated calls based on single Name, because generated VolumeID made those look as different devices for underlying device layer.

That's a good point. So there *is* a reason for using hashing after all. We definitely need to document that in the code so that we don't forget (again - at least I did...).

It sounds like we are stuck with the current approach because we need deterministic volume IDs that get created by the controller for cache volumes. We can't recover from a hash conflict via some counter either, because then we are no longer idempotent when the circumstances change.

So for now I propose that we:
- introduce a helper function to remove the code duplication
- fully document in the code all the constraints for that function

@okartau: can you take this issue?

**Comment by okartau** [comment]
I agree, let's abandon plans to use additional tricks, and stick to hashing as  this is the most elegant way. What we can easily change is move to SHA-2 from SHA-1, lowering chance of random collision and making attacking harder (pushing to future as there is no known breaking of SHA-2 yet known, right). 
So here is combined plan now:
- Introduce a helper function to remove the code duplication
- Fully document in the code all the constraints for that function
- Move to SHA-2. SHA-224 or SHA-256 seem as suitable choices: we dont want/cant afford too long IDs
- Include part of name, for example: VolumeID = first_N_chars_from_Name + sha256(Name)
- Return error on VolumeID collision. I don't see other code candidates than Internal=13. CSI spec does not cover such scenario with defined error code. There is tempting ALREADY_EXISTS with Recovery:"Caller MUST fix the arguments or use a different name before retrying." where "use different name" part would get us over random collision state, but as it goes too much out of scope of "already exists" I think better not to go there.

**Comment by okartau** [comment]
This was covered by change in #523, plus another smaller fix later, so I think we can close?
