### ISSUE TITLE
low pass rate of pmem-csi-periodic CI job

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#529]
pmem-csi-periodic has failed most of recent runs, 1/5 OK.
The failure seems to come in one (but different) of "production" type stages, when timeout of 45 min is reached.
That is in contrast with PR-triggered jobs which mostly work, so either there is something different happening in production tester, or perhaps (as we re-use test cluster) the state of cluster somehow degrades when more is performed? (as PR-based jobs runs just few sessions on same cluster) and reports OK).

**Comment by okartau** [comment]
I looked into logs of failing part of https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi-periodic/458/
which starts at 22:44:19

I cant see immediate error spelled out (can someone?), but is cluster in good shape when testing starts?
Few test are SKIPPED, then gotests is started,  tar/untar is performed.
```
Running in PMEM-CSI pod pmem-csi-node-b4g8
```
driver-registrar and pmem-driver pods reach RUNNING state at 22:45:04.
Then, there is first log after startup from driver.
But after that, there are only "CONNECTING....Reconnected" logs from pmem-csi driver,
plus output from top and df, until timeout kills the stage 45 min later.
Why is testing not running?

**Comment by pohly** [comment]
It is suspicious that `pmem-csi-node-mjwdq` terminates at around the same time as the go testing starts. Why does it do that? Was the node getting overloaded (but why?) and Kubernetes started to remove pods?

A new node pod is getting created and that's where testing is about to start, but somehow executing this command never completes:
```
 [1mSTEP[0m: Running in PMEM-CSI pod pmem-csi-node-b4g8l
 Feb  5 22:45:00.131: INFO: ExecWithOptions {Command:[/bin/sh -c tar -xf - &&if _work/test.test -h 2>&1 | grep -q ginkgo; then TEST_WORK=_work _work/test.test -test.v -ginkgo.v; else TEST_WORK=_work _work/test.test -test.v; fi] Namespace:default PodName:pmem-csi-node-b4g8l ContainerName:pmem-driver Stdin:0xc000010ef8 CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
```

We don't have enough information about the failure. We need a copy of the kubelet log. It's probably too large to dump all the time, so we should capture it only after a timeout.

**Comment by pohly** [comment]
Here's and idea how that additional log gathering may work:
```
void TestInVM(deviceMode, deploymentMode, distro, distroVersion, kubernetesVersion) {
    try {
...
   catch (Exception ex) {
       println("Gathering additional log output after failure.")
       // Gather kubelet logs via ssh + journalctl.
       // Get log from system pods via "kubectl logs".
   } finally {
       ...
   }
}
```

Untested, YMMV. To test it, rip out the actual test execution and just replace with a sleep and shorten the timeout for the job.

**Comment by okartau** [comment]
Seems merge of #548 improved  the pass rate, there was been 4/4 OK runs after that (plus, few more good ones in another Jenkins system that I use for additional debugging). On top of that state,  change of #556 was merged, which may affect testing outcome, so let's monitor for few more days before deciding about action on this issue.

**Comment by okartau** [comment]
There were multiple passes to fix this, a bigger re-organization of testing stabilized the tests, plus later separation of controller to run on master and not on worker, worked around CNI-related connectivity issue on Clear.
Recently, job has been stable, so closing  this issue.
