### ISSUE TITLE
should study how to provision raw device

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#53]
In a recent design mtg, it was pointed out we should try to implement a mode where Pmem-CSI driver provisions raw-mode device instead of volume with formatted-mounted file system

**Comment by avalluri** [comment]
I made changes needed to support "raw block device/volume". The changes are here: https://github.com/avalluri/pmem-CSI/commit/027af452b5de08ba36215dbe863692ad471b25aa

But currently, both Kubernetes and CSI has support for exposing only block devices, no support for "character/special devices". This means we can only support PMEM devices created in `fsdax` mode, not `devdax/dax` devices. As @okartau  mentioned `dax` mode exposes character device.

But, my feeling is that `fsdax` block device is not so useful for PMEM aware applications as they won't get benefited without having `dax` supported filesystems.

**Comment by pohly** [comment]
Amarnath Valluri <notifications@github.com> writes:
> I made changes needed to support "raw block device/volume". The changes are here: https://github.com/avalluri/pmem-CSI/commit/027af452b5de08ba36215dbe863692ad471b25aa
>
> But currently, both Kubernetes and CSI has support for exposing only
> block devices, no support for "character/special devices".

Does it matter what it is called in the spec? Yes, it talks about "block
device API", but neither Kubernetes nor the Kubernetes-CSI sidecar
containers care about the content of that block device and whether it
really is a traditional block device.

> As @okartau  mentioned `dax` mode exposes character device.

I think it is fine to expose that to an app, if the app explicitly asks
for it. We can do that via a storageclass parameter.

**Comment by avalluri** [comment]
> Does it matter what it is called in the spec? Yes, it talks about "block device API", but neither Kubernetes nor the Kubernetes-CSI sidecar containers care about the content of that block device and whether it really is a traditional block device.

I even was in the same thinking and went ahead and tried, but later realized that Kubernetes is trying [losetup](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/volumepathhandler/volume_path_handler_linux.go) on the device while mounting the device for Pod. This step fails for a character device.

**Comment by pohly** [comment]
Amarnath Valluri <notifications@github.com> writes:

>> Does it matter what it is called in the spec? Yes, it talks about "block device API", but neither Kubernetes nor the Kubernetes-CSI sidecar containers care about the content of that block device and whether it really is a traditional block device.
>
> I even was in the same thinking and went ahead and tried, but later
> realized that Kubernetes is trying
> [losetup](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/volumepathhandler/volume_path_handler_linux.go)
> on the device while mounting the device for Pod. This step fails for a
> character device.

"while mounting the device for Pod" - why should it mount the device?
Raw block devices don't get mounted.

That sounds like a bug. Can you file it against Kubernetes and discuss
with upstream?

**Comment by avalluri** [comment]
Below is the code comment above calling [BlockVolumePathHandler.AttachVolume()](https://github.com/kubernetes/kubernetes/blob/7dfcacd1cfcbdfe74b28f2473fb107e9a47ec905/pkg/volume/util/operationexecutor/operation_generator.go#L1046) call, which creates the loop device for block volume:

// Take filedescriptor lock to keep a block device opened. Otherwise, there is a case
// that the block device is silently removed and attached another device with same name.
// Container runtime can't handler this problem. To avoid unexpected condition fd lock
// for the block device is required.

**Comment by okartau** [comment]
Can we achieve what is asked by implementing support for VolumeMode: block ?
VolumeMode is marked beta in 1.13, is it fully supported in 1.14 and later?
At least I see VolumeMode:nil option as part of pvc creation in e2e testing using 1.15.
And if I get the idea right, VolumeMode:block mode means similar to what pmem-csi does already, but skipping mkfs and mounting? But then how the provisioning cycle is supposed to work without Stage and Publish?

**Comment by okartau** [comment]
Does recent addition of block-mode volume support cover this requirement?

**Comment by pohly** [comment]
I think it does. Let's close it and open another issue if we get a more specific requirement for some other kind of raw block device.
