### ISSUE TITLE
e2e: runGoTest tries to run in pod which has been terminated

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#544]
I found one pattern where pmem-csi-periodic fails. 
"tar -cf" on host remains running, blocked on write to stdout which is connected to pipe.
"tar" parent is e2e.test which busyloops but does not proceed, nor fail.
Jenkins pipeline stage times out.
It seems runGoTest tries to start another end of pipe (tar xf) on a pod which has terminated few seconds earlier, and there is no failing path for this condition.
Here is some meaningful events of this chain, extracted from big log (and additional details from worker1 socat-pod log).

----------------------------------------
00:11:27 go test DEVICEMODE=direct is started (stage: testing 1.14 direct)
driver pod 2nk8k was running during previous stage, worker1

========= driver pod 2nk8k (worker1) terminated 3sec after "go test" start ====
pmem-csi-node-2nk8k: I0306 00:11:30.169714 Caught signal terminated, terminating.
pmem-csi-node-2nk8k: I0306 00:11:30.170451 Server on 'tcp://172.17.0.5:10001' stopped
pmem-csi-node-2nk8k: I0306 00:11:30.171620 Server on 'unix:///var/lib/pmem-csi.intel.com/csi.sock' stopped

========= Starting new E2E suite ====
00:11:31.220 Running Suite: PMEM E2E suite
runGoTest -> RunInPod
00:11:32.322 STEP Compiling with:
=== run on host "tar -cf - _work/test.test _work/evil-ca _work/pmem-ca" with stdout connected to pipe.
=== and try to start tar -xf in pod 2nk8k: (NOTE: which has been deleted 2 sec ago)
00:11:33.806 STEP: Running in PMEM-CSI pod pmem-csi-node-2nk8k
00:11:33.759 INFO: ExecWithOptions {Command:[/bin/sh -c tar -xf...

======== 10 seconds of GRPC connect failures, 11:34 -- 11:44
00:11:34.203552   ccResolverWrapper: sending new addresses to cc: [{172.17.0.5:9735 0  <nil>}]
00:11:34.203616   addrConn: tryUpdateAddrs curAddr: { 0  <nil>}, addrs: [{172.17.0.5:9735 0  <nil>}]
00:11:34.203700   grpc: addrConn.createTransport failed to connect to {172.17.0.5:9735 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 172.17.0.5:9735: operation was canceled"

====== on worker1, pod-test repeats during 00:11:30--00:11:43: connect(5, AF=1 "/pmem-csi/csi.sock", 20): No such file or directory,
this fits the picture as during that window pod was not running on worker1

00:11:44.588 pod event: DELETED: default/pmem-csi-node-2nk8k

"tar -cf..." remains blocked on write() to stdout on host (pipe);
e2e.test keeps running at 100% of one core;
Pipeline stage times out in specified time and whole pipeline fails.

**Comment by okartau** [comment]
Interesting question is, what is returned by
```
pods, err := f.ClientSet.CoreV1().Pods("default").List(metav1.ListOptions{LabelSelector: label.String()})
```
in runGoTest.
It seems to run during window when pod itself has terminated, but kubectl would still show it, right?
(as "DELETED" mark is only printed at 00:11:44, thats 14 seconds after pod itself logged "terminated")
Does List() report pods which are in any state, like Terminating etc.?

**Comment by pohly** [comment]
> ========= driver pod 2nk8k (worker1) terminated 3sec after "go test" start ====
> pmem-csi-node-2nk8k: I0306 00:11:30.169714 Caught signal terminated, terminating.

The million dollar question now is: *why* was it terminated? Is there anything in the kubelet log at around that time that might explain this?

Normally, control loops deal with such unexpected events. But tests are a lot simpler and follow a pattern of "create pod, use pod, delete pod" or in this case "find pod, use pod". There's no control loop that retries.

> Does List() report pods which are in any state, like Terminating etc.?

Yes. That's how you find out which pods are terminating... if they weren't listed, how would you find them?

**Comment by okartau** [comment]
I think that it's terminated because our own testing flow makes/refreshes deployment by TEST_DEVICEMODE, and thats actually very important it gets terminated, as it runs in LVM mode, but starting test stage needs driver to be in direct mode, so we can not continue with previous driver.
I was first thinking we have issue there that we continue with previous driver, but seems I was not right, the deployment that runs near start of stage, has effect of changing the driver pods, right?

**Comment by okartau** [comment]
> Yes. That's how you find out which pods are terminating... if they weren't listed, how would you find them?

but isnt that the problem here? We list all pods and pick first one, and start activity there, but it happened to be Terminating. We should not pick such pod.

**Comment by pohly** [comment]
There is code which waits for PMEM-CSI to be running: https://github.com/intel/pmem-csi/blob/1373e404c74f0b973016ac3af91b59766ea55bf9/test/e2e/e2e.go#L170-L223

And now that I look at it, I did even point out one loophole:
> the annotation might be from a previous
> successful registration of the driver. For a fresh cluster as in the CI
> the check should be good enough.

But now we now longer run in "a fresh cluster", so this check is failing. We need something better.

In a related note, I suspect that we will have to move away from pre-installing the PMEM-CSI driver in the cluster before starting the E2E test. That's because with the upcoming operator feature we'll have to try out a lot more different deployment variants. We probably don't want to run all tests against all deployments (that may be too slow) and we also don't want to redeploy for each test (also too slow).

My current thinking is that we keep track in the cluster what's currently running and then tear it down and re-deploy only when needed. Let me see whether I can get that working next week...
