### ISSUE TITLE
Jenkins job logs are big

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#563]
After some commit around March-26, Jenkins job console logs size increased significantly.
I think the trigger was changed e2e testing.
pmem-csi-periodic, where logs used to be 22...25 MB, now has sizes 180...280 MB,
so we see about 10-fold increase.
```
-rw-r--r-- 1 ubuntu ubuntu  24M Mar 24 22:10 558/log
-rw-r--r-- 1 ubuntu ubuntu  28M Mar 25 10:19 559/log
-rw-r--r-- 1 ubuntu ubuntu 245M Mar 26 03:30 560/log
-rw-r--r-- 1 ubuntu ubuntu 237M Mar 26 15:31 561/log
-rw-r--r-- 1 ubuntu ubuntu 229M Mar 27 03:35 562/log
-rw-r--r-- 1 ubuntu ubuntu 228M Mar 27 15:46 563/log
-rw-r--r-- 1 ubuntu ubuntu 276M Mar 28 03:34 564/log
-rw-r--r-- 1 ubuntu ubuntu 187M Mar 28 15:35 565/log
-rw-r--r-- 1 ubuntu ubuntu 213M Mar 29 03:33 566/log
-rw-r--r-- 1 ubuntu ubuntu 187M Mar 29 15:16 567/log
-rw-r--r-- 1 ubuntu ubuntu  21M Mar 29 23:20 568/log
-rw-r--r-- 1 ubuntu ubuntu 228M Mar 30 15:16 569/log
-rw-r--r-- 1 ubuntu ubuntu 277M Mar 31 03:40 570/log
-rw-r--r-- 1 ubuntu ubuntu 219M Mar 31 15:15 571/log
-rw-r--r-- 1 ubuntu ubuntu 184M Apr  1 03:31 572/log
-rw-r--r-- 1 ubuntu ubuntu 211M Apr  1 15:35 573/log
-rw-r--r-- 1 ubuntu ubuntu 192M Apr  2 03:09 574/log
```

I tried to look into some 200+ MB logs of pmem-csi-periodic, but I dont see easy reason there, just lots of testing output. Did we increase amount of tests with recent e2e change ?

In PR-s the picture is not so clear.
Overall, a PR job should produce much shorter log than periodic, as not all stages run. That makes it especially interesting what happened in #561 

In one end #562 run shows relatively moderate 39 MB log file.

But on another, my trial about 1.18 in #561 is bad example with 360 MB log file. A read attempt of that log triggered Jenins OOM ("java.lang.OutOfMemoryError: Java heap space") yesterday and I had to restart jenkins (the out of mem can be also contrinuted by 7-weeks uptime)
But #561 is not good study example as it changes Jenkinsfile and replaces regular 1.15 testing with 1.18 (experimental) (does 1.18 add some big ouput?). I will take closer look.

Seems, getting very big logs from Jenkins GUI is problematic, it is slow and times out, and
seems also to trigger Java heap OOM in some cases.

**Comment by pohly** [comment]
> Did we increase amount of tests with recent e2e change ?

I think we test now more on Clear Linux. That used to be limited to lvm production testing, while now it covers the whole range.

Before: https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/job/devel/155/testReport/
After: https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/job/devel/166/testReport/

**Comment by okartau** [comment]
We run repeated e2e tests without re-creating cluster now right?
We seem to have repeated (older) log blocks, that may well explain the multi-fold increase.
I noticed that when I was running my "repeat-n-times-e2e" script a while ago, that log output from each next round got bigger linearly, as it included the log of previous rounds.

**Comment by pohly** [comment]
> We seem to have repeated (older) log blocks

You mean the log output of the PMEM-CSI pods? That should not have increased because each round of testing starts with a new deployment of those pods and thus new logs.

Do you have an example where log output is repeated?

**Comment by okartau** [comment]
> Do you have an example where log output is repeated?

In log of recent #565 run 1, there are many repeating blocks.
I used this: 
1. downloaded the log file as log-pr565
2. strip the 1st column where jenkins timestamp makes every line (almost) unique:
`$ cat log-pr565 |cut -f 1 -d ' ' --complement > log-pr565-nofirst`
3. count equal lines, sorted by repeat count
`cat log-pr565-nofirst |sort |uniq -c |grep -vE '^\s*1 ' |sort -n`

(yes one can combine those two lines but I separated them for working more on stripped file)

This simple method does not deal with blocks (one can create more sophisticated filter to analyze blocks), but it is already visible that certain blocks repeat 34,37,49,59,61,62 times, and it is not difficult to see from output which blocks these are.
The "winner" is this 16-line block that first appears at line 91286 and is repeated 62 times:
```
pmem-csi-node-d72x9/driver-registrar: I0402 16:41:32.086375       1 main.go:110] Version: v1.1.0-0-g80a94421
pmem-csi-node-d72x9/driver-registrar: I0402 16:41:32.086588       1 main.go:120] Attempting to open a gRPC connection with: "/pmem-csi/csi.sock"
...
```

I think we can outrule the possibility that log actually has tens repeating lines reported on same microsecond timestamp.
I haven't analyzed older logs using same method, but I can go back and calculate some "repetition metrics" on older logs as well to see has this changed lately.

**Comment by pohly** [comment]
> In log of recent #565 run 1, there are many repeating blocks.

To avoid ambiguity, here's a URL: https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/view/change-requests/job/PR-565/1/execution/node/91/log/?consoleFull

> The "winner" is this 16-line block that first appears at line 91286 and is repeated 62 times:

Thanks for digging this out. I can confirm that the same driver-registrar output seems to get dumpled multiple times. I'll check why podlogs seems to be started multiple times.

**Comment by pohly** [comment]
> I'll check why podlogs seems to be started multiple times.

"why" is a bit hard to answer. Probably we simply loose the connection to the API server:
https://github.com/kubernetes/kubernetes/blob/873fe1478a79841349aef6ed4b6907dcb7a179b1/test/e2e/storage/podlogs/podlogs.go#L214

When that happens, logging for the pod stops and then resumes later *at the beginning*.

What's missing is the code for "we have printed this line already". This is going to be tricky because lines don't have a unique ID - the code will basically have to compare line content.

**Comment by pohly** [comment]
One reason for duplicate output are our restart tests. Logging stops when the container is terminated, but then the next attempt to log picks up the output of the dead container again. This can repeat a few times until eventually the container really restarts and produces new output.

The simplest solution might be to print output for the same container instance only once when it is dead. That doesn't cover the case where printing restarts for a container that kept running, but that should be less common.

**Comment by okartau** [comment]
#565 was merged so improvement is expected, but let's keep this open for some time, I want to take a look at pmem-csi-periodic logs.

**Comment by okartau** [comment]
pmem-csi-periodic still has to reach the state it fully runs, but I can estimate the log is now about 60..70 MB, which is not small, but at least the multi-hundred MB log problem is fixed, and there is no repeated blocks, so issue can be closed. Future improvements in reducing log size are still welcome.
