### ISSUE TITLE
test: false negative for volume leak check

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#568]
After aborting a test run on a local cluster, I must have had one local volume left over from that aborted test. The next test then failed like this:
```
ESC[91mESC[1m• Failure in Spec Teardown (AfterEach) [47.146 seconds]ESC[0m
lvm-testing
ESC[90m/nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/deploy/deploy.go:501ESC[0m
  sanity
  ESC[90m/nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/deploy/deploy.go:488ESC[0m
    ESC[91mESC[1mPMEM-CSI [AfterEach]ESC[0m
    ESC[90m/nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/storage/sanity.go:212ESC[0m
      stores state across reboots for single volume
      ESC[90m/nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/storage/sanity.go:258ESC[0m

      ESC[91msame volumes before and after the test
      Expected
          <map[string][]string | len:3>: {
              "LVM Volumes on Node 1": [
                  "unset--c80a6509c9e210ba16c4943ae726af8a69c5a144be48e5fdeebcc9ac ndbus0region0fsdax -wi-a----- 36.00m",
              ],
              "LVM Volumes on Node 2": [""],
              "LVM Volumes on Node 3": [""],
          }
      to equal
          <map[string][]string | len:3>: {
              "LVM Volumes on Node 1": [
                  "unset--c80a6509c9e210ba16c4943ae726af8a69c5a144be48e5fdeebcc9ac ndbus0region0fsdax -wi-ao---- 36.00m",
              ],
              "LVM Volumes on Node 2": [""],
              "LVM Volumes on Node 3": [""],
          }ESC[0m

      /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/storage/sanity.go:1066
```

Note that the volumes *are* the same, i.e. no new volume has leaked. What has changed are the attributes (`-wi-a-----` ->`-wi-ao----`).

This happened during the reboot test. Either those attributes must not change (and we need to investigate this situation), or they may change and then shouldn't be included in the comparison.

**Comment by okartau** [comment]
attribute `o` means "device open". Typically, this is set when Logical Volume for example is mounted, and unset if volume is not mounted.

**Comment by pohly** [comment]
So it was open before and now no longer is? I guess that can happen if the volume was mounted before without Kubernetes knowing about it, so rebooting the node led to an umounted volume.

That's good enough for me, let's consider this a non-issue.
