### ISSUE TITLE
e2e test "is secure" at tls.go:46 failed multiple times in pmem-csi-periodic

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#570]
Two consecutive pmem-csi-periodc runs, 582 and 583
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi-periodic/582/testReport/junit/fedora-1_16.direct-testing/TLS/controller_is_secure/
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi-periodic/583/testReport/junit/fedora-1_16.direct-testing/TLS/controller_is_secure/ 

both failed with error:
```
/mnt/workspace/pmem-csi-periodic/test/e2e/tls/tls.go:46
ports found
Expected
    <[][]string | len:0, cap:0>: nil
not to be empty
/mnt/workspace/pmem-csi-periodic/test/e2e/tls/tls.go:161
```

Note that although the short error display in Jenkins makes attempt to show relevant part of log, it actually does not show the part with some info about real reason (nmap output). I see it when I look into full log file:
```
[2020-04-06T09:40:47.445Z] Starting Nmap 7.80 ( https://nmap.org ) at 2020-04-06 09:40 UTC
[2020-04-06T09:40:47.445Z] Nmap done: 1 IP address (0 hosts up) scanned in 2.03 seconds
```

as we can see, nmap tells the host to be scanned, was not detected to be up.

The line invoking nmap was:
```
nmap --script +ssl-enum-ciphers --open -Pn pmem-csi-controller-0.pmem-csi-controller.default
```

For comparison, when nmap runs OK, it shows scan output followed by
`Nmap done: 1 IP address (1 host up) scanned in 0.50 seconds`

**Comment by pohly** [comment]
> Note that although the short error display in Jenkins makes attempt to show relevant part of log, it actually does not show the part with some info about real reason (nmap output).

That's odd. https://github.com/intel/pmem-csi/blob/d03cf74be569b333e274c2aaee5f732c0b49d45d/test/e2e/pod/exec.go#L59-L60 writes to `GinkgoWriter` just as the E2E framework does, and those log messages (like ">>> kubeConfig:") are included.

> nmap tells the host to be scanned, was not detected to be up.

This might be a misleading message. We disable host discovery with `-Pn`; probably this just means that even port scanning didn't find any open ports.

I wonder whether there's a race condition between "pod is running" and "incoming traffic gets through". In that case a simple retry loop may be enough to fix this issue.

**Comment by pohly** [comment]
> Note that although the short error display in Jenkins makes attempt to show relevant part of log, it actually does not show the part with some info about real reason (nmap output).

I think you just overlooked it.

https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi-periodic/582/testReport/junit/fedora-1_16.direct-testing/TLS/controller_is_secure/ contains "Nmap done: 1 IP address (0 hosts up) scanned in 1.61 seconds".

It's followed by "�[1mSTEP�[0m: delete the pod" on the same line, something that PR #604 fixes by adding a newline after dumping command output.

That PR also tries to fix the TLS test flakes by retrying the nmap invocation if no ports were found. Let's keep this issue open until we are confident that this change really helped.

**Comment by pohly** [comment]
Seems to work.
