### ISSUE TITLE
operator: when a user tries to modify static fields, there should be some feedback

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#580]
When trying to update `pmemPercentage`, the operator reverts that change. However, there is no feedback to the user that this is happening:

```
$ cat operator/examples/pmem-csi.intel.com_v1alpha1_deployment_cr.yaml | /nvme/gopath/src/github.com/intel/pmem-csi/_work/pmem-govm/ssh.0 kubectl apply -f -
deployment.pmem-csi.intel.com/example-deployment configured

$ kubectl describe deployments.pmem-csi.intel.com
...
  Pmem Percentage:    60
  Provisioner Image:  quay.io/k8scsi/csi-provisioner:v1.2.1
Status:
  Phase:  Running
Events:   <none>
```

As `kubectl apply` cannot know about this, I would expect to see some event posted for the reverting.

**Comment by avalluri** [comment]
Yes, I agree. I will take this part of #542

**Comment by pohly** [comment]
This has become obsolete because we no longer have immutable fields (PR #623).
