### ISSUE TITLE
operator: test changing fixed fields while operator is stopped

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#582]
When the operator encounters an invalid change (like modifying pmemPercentage) it rolls back the change. We have tests for that while the operator is running, but we also need tests for the situation that the change is made while the operator is stopped.

This needs to built on top of https://github.com/intel/pmem-csi/issues/579

**Comment by pohly** [comment]
@avalluri said
> The changes kept in the deployment, till the operator starts and reconciles the deployment changes.

I am not exactly sure what that means. The deployments.pmem-csi.intel.com object should get modified while the operator is down; I'm not aware of a mechanism that stores changes there for processing by an operator.

The operator then needs to reconcile the modified deployments.pmem-csi.intel.com object with the statefulset object that it created. I've not found the code which reads pmemPercentage from the running driver deployment.

BTW, as can be seen here, the term "deployment" is ambiguous. I'm wondering whether we should rename our API object to reduce the risk of confusing it with other meanings of the word ("deployment of an app", the Kubernetes "deployment" type).

**Comment by avalluri** [comment]
> I am not exactly sure what that means. The deployments.pmem-csi.intel.com object should get modified while the operator is down; I'm not aware of a mechanism that stores changes there for processing by an operator.

I meant that the changes get stored in the API server and when the deployment gets reconciled on the operator restart.

> The operator then needs to reconcile the modified deployments.pmem-csi.intel.com object with the statefulset object that it created. I've not found the code which reads pmemPercentage from the running driver deployment.

Yes, you are right, this case was not handled, the current code only finds the changes about know deployments. I fixed this gap in #584.

**Comment by pohly** [comment]
This has become obsolete because we no longer have immutable fields (PR #623).
