### ISSUE TITLE
operator: does not update deployment with updated user-supplied certificates

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#596]
https://github.com/intel/pmem-csi/blob/4fde6ffe37e067e688b2be1cfc8f4bd4b6246804/pkg/pmem-csi-operator/controller/deployment/controller_driver.go#L97-L176

lacks code for updating the certificates.

**Comment by pohly** [comment]
Maintaining the change detection and writing code which then selectively updates existing objects seems quite a bit of work and, as seen here, it is easy to miss things.

Let me propose a different approach for reconciliation:
- with the updated deployment configuration, generate all objects
- for each object:
  - if it does not exist, create it
  - if it exists, generate a JSON patch for the spec;
    - if that patch is empty, do nothing
    - otherwise patch the object
- delete all obsolete objects

This code only needs to be written once and then requires no further maintenance.

If patching is seen as too complicated, then simply do a deep-equal comparison of the spec and a normal update with new spec if there was a difference. Whatever is easier to implement... performance is irrelevant given the small size and number of objects and the infrequent deployment changes.

**Comment by avalluri** [comment]
> Let me propose a different approach for reconciliation:
@pohly Shall we try this approach for post-v.0.7.0 release as it needs a bit of brainstorming. 

I fixed this with current change detection logic: https://github.com/intel/pmem-csi/pull/610/commits/2c5cd30646d167722f424c8d99d6e0331e9f494d

**Comment by pohly** [comment]
> > Let me propose a different approach for reconciliation:
> > ...
>
> Shall we try this approach for post-v.0.7.0 release as it needs a bit of brainstorming.

Yes.

**Comment by pohly** [comment]
Fixed in https://github.com/intel/pmem-csi/commit/2c5cd30646d167722f424c8d99d6e0331e9f494d
