### ISSUE TITLE
operator API v1alpha2: revise Status

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#611]
We should align with https://github.com/kubernetes/enhancements/pull/1624.

**Comment by pohly** [comment]
@avalluri please describe what you intend to do regarding the status field in the CRD.

**Comment by avalluri** [comment]
@pohly, here is the draft of the new status type roughly look:

```
// DeploymentConditionType type for representing a deployment status condition
type DeploymentConditionType string

const (
	// CertsVerified means the provided deployment secrets are verified and valid for usage
	CertsVerified DeploymentConditionType = "CertsVerified"
	// CertsReady means secrests/certificates required for running the PMEM-CSI driver
	// are ready and the deployment could progress further
	CertsReady DeploymentConditionType = "CertsReady"
	// DriverDeployed means that the node driver deamonset got created
	DriverDeployed DeploymentConditionType = "DriverDeployed"
)

// +k8s:deepcopy-gen=true
type DeploymentCondition struct {
	// Type of condition.
	Type DeploymentConditionType `json:"type"`
	// Status of the condition, one of True, False, Unknown.
	Status corev1.ConditionStatus `json:"status"`
	// Message human readable text that explain why this condition is in this state
	// +optional
	Message string `json:"reason,omitempty"`
	// Last time the condition was probed.
	// +optional
	LastUpdateTime metav1.Time `json:"lastUpdateTime,omitempty"`
}

type DriverType string

const (
	ControllerDriver DriverType = "ControllerDriver"
	NodeDriver       DriverType = "NodeDriver"
)

// +k8s:deepcopy-gen=true
type DriverStatus struct {
	// Type represents type of the driver: controller or node
	Type DriverType `json:"type"`
	// Status represents the driver status : Ready, NotReady
	Status string `json:"status"`
	// Reason represents the human readable text that explains why the
	// driver is in this state.
	Reason string `json:"message"`
}

// +k8s:deepcopy-gen=true
// DeploymentStatus defines the observed state of Deployment
type DeploymentStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make operator-generate-k8s" to regenerate code after modifying this file

	// Phase indicates the state of the deployment
	Phase DeploymentPhase `json:"phase,omitempty"`
	// Conditions
	Conditions []DeploymentCondition `json:"conditions,omitempty"`
	Components []DriverStatus        `json:"components,omitempty"`
	// LastUpdated time of the deployment status
	LastUpdated metav1.Time `json:"lastUpdated,omitempty"`
}
```

I initially thout of including all sub-resources(roles, rolbebidnings, services, etc.) created for the deployment, but I am kind of decided to limit that to just keep node & controller driver status.

**Comment by pohly** [comment]
> // Type represents type of the driver: controller or node
>Type DriverType `json:"type"`

Is the plan to have more than one entry with type "node"?

If yes, how does the user know which node the status belongs to? If no, does it make sense to have `Components []DriverStatus` (an array) when there are always just two entries?

How does the operator determine whether the "controller" or "node" is "ready"? You need to explain the semantic in your API, not just list the values.

**Comment by avalluri** [comment]
> > // Type represents type of the driver: controller or node
> > Type DriverType `json:"type"`
> 
> Is the plan to have more than one entry with type "node"?

No, It is combined state of all the node(s)/daemonset. The 'Reason' field supposed to hold the details of how many nodes are in running state out of total of nodes. 

> If no, does it make sense to have `Components []DriverStatus` (an array) when there are always just two entries?

The array was result fo the initial design to hold all sub-resources state. Left like that, assuming that could be extendable to the original idea if needed. Otherwise we can split into two entries - ControllerDriver and NodeDriver.

> How does the operator determine whether the "controller" or "node" is "ready"?

'Ready' here meaning that the Pods underneath the node DaemonSet, and StatefulSet are in 'Running' state.

**Comment by pohly** [comment]
Didn't make it into 0.8. Let's move it to 0.9.
