### ISSUE TITLE
operator: test unexpected shutdown

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#612]
The operator must work correctly even when the pod it runs in gets killed in the middle of some work.

This will be hard to test in an E2E test. What we can cover there is stopping/restarting the operator while it doesn't do any work, but hitting exactly the time when it is busy will be close to impossible.

What we can do instead is add error injection into the fake client: any interaction with the fake client is a point in time where we can kill the operator.

**Comment by pohly** [comment]
Didn't make it into 0.8. Let's move it to 0.9.

**Comment by avalluri** [comment]
> What we can do instead is add error injection into the fake client: any interaction with the fake client is a point in time where we can kill the operator.

I been thinking about this, and I am not clear if we can do this in our E2E test. Even if we introduce the fake client error injection, the operator running in the cluster does not interact with that fake client, or I miss something?

Instead, how about tests watching for the apiserver events on sub-resources created by the operator on a deployment, and kill the operator in event handler. And verify that open the operator restart that deployment still should be successful.  For example watch for 'CSIDriver' object creation, at this point we ensure that the operator is busy in serving a deployment.

**Comment by pohly** [comment]
> I been thinking about this, and I am not clear if we can do this in our E2E testing. Even if we introduce the fake client error injection, the operator running in the cluster does not interact with that fake client, or I miss something?

There's been a misunderstanding. When I talked about "fake client", I had already ruled out doing it during an E2E test and was thinking about a unit test. As you said, using the fake client in an E2E test makes no sense.

**Comment by avalluri** [comment]
> > I been thinking about this, and I am not clear if we can do this in our E2E testing. Even if we introduce the fake client error injection, the operator running in the cluster does not interact with that fake client, or I miss something?
> 
> There's been a misunderstanding. When I talked about "fake client", I had already ruled out doing it during an E2E test and was thinking about a unit test.

Okay, But it is not possible to test 'unexpected shutdown of the operator pod' in unit tests., as there will no operator pod itself :thinking:

**Comment by pohly** [comment]
> Okay, But it is not possible to test 'unexpected shutdown of the operator pod' in unit tests., as there will no operator pod itself

You can create one instance of it, let it reconcile until it hits the fake error and there throw a panic which you catch outside. Then create another instance that needs to continue where the previous one was interrupted.
