### ISSUE TITLE
operator: (re)configuration of CSI driver name

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#614]
Currently the driver name is part of the deployment spec and modifying it is allowed. However, the code which removes the old CSIDriver object after a name change is missing.

Two solutions:
1. https://github.com/intel/pmem-csi/issues/595 will solve it
2. remove the separate driver name from the spec and use the deployment object name as driver name

**Comment by pohly** [comment]
I might have been the one who suggested to make the driver name configurable. However, I'm now leaning more towards option 2.

@avalluri : what do you think?

**Comment by avalluri** [comment]
> @avalluri : what do you think?

I have no strong opinion on using deployment as CSI driver name, but if the concern is with removing the old driver object, I would propose making this field immutable.

**Comment by pohly** [comment]
Changing the driver name also has implications for existing volumes because they are tied to the driver name and the state dir used by the operator is `/var/lib/<driver name>`. We need to discuss how we want to handle this.

**Comment by pohly** [comment]
There's no guarantee that `/var/lib/<driver name>` isn't used by something else. Should we move to `/var/lib/pmem-csi.intel.com/<driver name>` or document the potential conflict?

**Comment by pohly** [comment]
We also need to add sanity checking of the deployment name: it must be short enough such that we can create additional objects with "name + suffix".

**Comment by pohly** [comment]
Resolved in PR #623.
