### ISSUE TITLE
pmem-csi-release job started to fail

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#621]
CI job started to fail at v0.6.38, two recent jobs failed. The reason is disk full during build:
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi-release/118/

Our builders have 30G as OS-disk and additional 64G mounted to /mnt (where Jenkins workspace is). I think that if we run out of space in docker build then we actually did fill the OS-part (/var/lib)

Here is captured 'df' from another worker session (just some ongoing build) for reference:
```
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  1.2M  3.2G   1% /run
/dev/sda1        29G   13G   17G  43% /
tmpfs            16G     0   16G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sda15      105M  3.6M  101M   4% /boot/efi
/dev/sdb1        63G   21G   39G  35% /mnt
tmpfs           3.2G     0  3.2G   0% /run/user/1000
tmpfs           3.2G     0  3.2G   0% /run/user/998
none            1.0G   54M  971M   6% /mnt/workspace/pmem-csi-periodic/_work/govm/data/pmem-csi-govm-master/etcd-tmpfs
overlay          29G   13G   17G  43% /var/lib/docker/overlay2/803b8c335ac7de39c6d78bc73e01ccfcc2726c332c3da727d868de1fc3f89936/merged
overlay          29G   13G   17G  43% /var/lib/docker/overlay2/ad6ba12b1668fc5c722c54f32ee3ff9e78e8a725609e32fc5c478f391808f14c/merged
overlay          29G   13G   17G  43% /var/lib/docker/overlay2/fb20a52ba57e56496d8c04a765bc3d2b881e6c6a78c6e2c87509279daa0b2b86/merged
```

**Comment by pohly** [comment]
I thought `/var/lib/docker` was already on the `/mnt` volume, but apparently not. Can you change that in the Jenkins machine startup script? A symlink might be all that it takes, because each machine starts with no `/var/lib/docker`.

**Comment by okartau** [comment]
I added mkdir /mnt/docker and linking /var/lib/docker to that, following builds will show

**Comment by okartau** [comment]
I triggered manually that job and peeked into worker, seems that plan works. Now docker data is located under /mnt, leaving rootfs with low use level:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        29G  2.1G   27G   7% /
tmpfs            16G     0   16G   0% /dev/shm
/dev/sda15      105M  3.6M  101M   4% /boot/efi
/dev/sdb1        63G  3.1G   57G   6% /mnt
overlay          63G  3.1G   57G   6% /mnt/docker/overlay2/fb4d8eaf6dd28a932e22f3b26fac6711d5176c2f6073ecc460df92d7217c5990/merged
```
job just started, we can tell the ultimate result after completion

**Comment by okartau** [comment]
That change may cause another trouble, /mnt may get full next. My local setup where I locally run pmem-csi-periodic, shows approx 50G is used by working directory, almost all of that is made up by govm images. By moving docker data to /mnt, we may overflow that now. We will see soon. If that happens, we may need bigger /mnt. Or, bigger rootfs with docker located back onto rootfs. Because now, if we dont put anything big on rootfs, we have 20G kind of wasted there (10G is plenty for just rootfs needs)

**Comment by okartau** [comment]
That build worked, also another pmem-csi-periodic. I monitored worker in early stages and saw about 80% of /mnt used, but I did not monitor for full build time.
I got idea, lets add one `df` at the end of build cycle, then we will always see state at least at the end point (or we can add multiple/periodic). I recall seen some df output in jobs logs, but when I look to recent pmem-csi-periodic logs, I see none, was that removed?

**Comment by okartau** [comment]
> I recall seen some df output in jobs logs, but when I look to recent pmem-csi-periodic logs, I see none, was that removed?

I was not looking good enough (did I just grep for df), of course it is there already, so no need to add. Sorting use of /mnt volume from recent pmem-csi-periodic shows max 76%, so not looking bad yet.
```
$ grep /dev/sdb1 log628 |sort -n -k 4 | tail -1
[2020-04-29T04:35:04.920Z] /dev/sdb1        63G   45G   15G  76% /mnt
```

Same analysis for rootfs shows we now use max 10% of it:
```
[2020-04-29T04:35:04.920Z] /dev/sda1        29G  2.7G   27G  10% /
```

**Comment by pohly** [comment]
It still fails, now with "/mnt/workspace/pmem-csi-release@tmp/durable-0db95c94: No space left on device". Can't we just ask for a larger SSD?

**Comment by okartau** [comment]
I can't see easily from config where the size of sdb is configured (or even, where the presence of it is configured). But I see where the size of OS disk (sda) is configured, it becomes 30G as default. I try to make that larger and see in coming build log does increasing work.

**Comment by okartau** [comment]
sda gets bigger with that change, good. Next I revert recently added symlink creation of docker dir, putting it back to rootfs, which is bigger now. That should give additional breathe room on both sides.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> I can't see easily from config where the size of sdb is configured (or
> even, where the presence of it is configured).

It might be part of the machine definition in Azure. Selecting a
"larger" machine might also give us a larger SSD.

**Comment by pohly** [comment]
@okartau this is resolved, right?

**Comment by okartau** [comment]
> this is resolved, right?

this is "yes with a but", i.e. original failure was fixed and job ran few times OK, but currently 3 most recent jobs failed again, in ndctl build ld reports "multiple defined" errors. We seem to build older ndctl-67 (I think we switched to v68 in devel) as we build release-0.6 branch

Should we continue handling failure here, or close this and create a new issue for new failures?

**Comment by pohly** [comment]
> currently 3 most recent jobs failed again, in ndctl build ld reports "multiple defined" errors

So the updated compilers in Clear Linux have problems building the older ndctl, which blocks our update path for Clear Linux base images. We should update ndctl also on the release-0.6 branch.

> Should we continue handling failure here, or close this and create a new issue for new failures?

Let's track it here.

**Comment by okartau** [comment]
> We should update ndctl also on the release-0.6 branch

What's the correct way, is it enough to cherry-pick a commit from devel and create a PR against release-0.6 branch, or is there some other preferred way?

**Comment by pohly** [comment]
> is it enough to cherry-pick a commit from devel and create a PR against release-0.6 branch

This is the right approach.

**Comment by okartau** [comment]
The latest pmem-csi-release job is OK after ndctl version was changed to 68, thus we can close this.
