### ISSUE TITLE
switching device mode

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#632]
One thing that I noticed recently: we use `/var/lib/<csi driver name>` for persistent information about volumes. This probably breaks badly when an admin reinstalls the driver in a different mode while keeping the driver name the same.

Instead of telling admins "don't do that", can we make the driver more resilient against such a situation?

A good first step would be to add the device mode to the volume information, instead of assuming that the volume is for the current mode.

Then we can either ignore the "wrong" volumes or perhaps support *both* modes in the driver at the same time, at least for existing volumes? Instead of putting "device mode" into the deployment parameters, it would become a per-volume parameter.

We still need to figure out when to create volume groups, though.

Some work was done for this, but some work remains:
- When changing the device mode while a pod is using a volume, deleting the pod no longer works because the volume operations during the pod removal will fail. To recover, an admin has to revert back to the original device mode.

**Comment by avalluri** [comment]
> One thing that I noticed recently: we use `/var/lib/<csi driver name>` for persistent information about volumes. This probably breaks badly when an admin reinstalls the driver in a different mode while keeping the driver name the same.

This should not be a problem when considering the state reloading, On reloading of state volumes, we check with device manager if the volume really exists with that id, if not found we assume that this as a stale entry and remove from the state. 

But the question is, on mode change, how should really the driver deal with those pre-created volumes, exit with failure or delete them? Otherwise, they gets leaked.

**Comment by pohly** [comment]
> This should not be a problem when considering the state reloading, On reloading of state volumes, we check with device manager if the volume really exists with that id, if not found we assume that this as a stale entry and remove from the state.

Which is problematic. Suppose there is a volume in LVM mode and the admin accidentally (re)installs the driver in direct mode. That now removes the volume state. When admin corrects his mistake and goes back to LVM, is the volume still usable? From what you said, it probably isn't.

> But the question is, on mode change, how should really the driver deal with those pre-created volumes, exit with failure or delete them? Otherwise, they gets leaked.

Ideally, the driver continues to support using them in pods and deleting them. The second-best solution is to ignore them, which then allows the admin to go back to the old deployment, either to clean up or permanently (if switching was a mistake).

**Comment by avalluri** [comment]
> Which is problematic. Suppose there is a volume in LVM mode and the admin accidentally (re)installs the driver in direct mode. That now removes the volume state. When admin corrects his mistake and goes back to LVM, is the volume still usable? From what you said, it probably isn't.
> 
> >
Yes, in this case what about if the driver startup fails with appropriate error so that admin can revert that mode change, he would clean the volumes and restart the driver in desired mode.

**Comment by pohly** [comment]
> Yes, in this case what about if the driver startup fails with appropriate error so that admin can revert that mode change, he would clean the volumes and restart the driver in desired mode.

Why is that better than ignoring the volumes in the wrong mode? Ignoring them is more flexible because it allows temporarily switching between modes.

Either way, both approaches depend on recording the mode in the on-disk parameters. We should add that before 0.7.0, then we can still add better handling of this situation later on.

**Comment by pohly** [comment]
In 0.7, let's ensure that volumes remain usable when switching from one mode to another and back.

In the future, let's ensure that pods and volumes of the other mode can be deleted after switching modes.

**Comment by pohly** [comment]
> In 0.7, let's ensure that volumes remain usable when switching from one mode to another and back.

Tests for this include (in increasing complexity):
- create volume, switch mode, switch back, use volume in pod, delete
- create volume, switch mode, try to delete volume and check for error, switch back, delete
- create volume, start pod, switch mode, try to delete pod, check that this fails, switch back, delete

**Comment by pohly** [comment]
@avalluri wrote in https://github.com/intel/pmem-csi/pull/677#discussion_r438672363
> Node stage and publish still might not work. I mean:
> 
> -  start the driver in lvm
> -  Create volume
> -    Run application using that volume
> -   switch driver mode to ndctl
> -    restart the application
>
> This supposed to fail.

**Comment by pohly** [comment]
Fail how?

**Comment by pohly** [comment]
We have done enough to release 0.7.0 (= change on-disk state), but should continue to enhance this.

**Comment by avalluri** [comment]
> Fail how?

`dm.GetDevice()` calls in `nodeserver.go` still fails as they couldn't recognize volumes created by other device manager.

**Comment by pohly** [comment]
What we need to document here in the issue is the user-visible effect, not what happens under the hood.

**Comment by pohly** [comment]
@valluri wrote:
> `dm.GetDevice()` calls in `nodeserver.go` still fails as they couldn't recognize volumes created by other device manager.

I replied:
> What we need to document here in the issue is the user-visible effect, not what happens under the hood.

@avalluri Is this a correct summary?

"When changing the device mode while a pod is using a volume, deleting the pod no longer works because the volume operations during the pod removal will fail. To recover, an admin has to revert back to the original device mode."

**Comment by avalluri** [comment]
> "When changing the device mode while a pod is using a volume, deleting the pod no longer works because the volume operations during the pod removal will fail. To recover, an admin has to revert back to the original device mode."

Yes, this is the right description.

**Comment by pohly** [comment]
Remaining work can be addressed in 0.9.
