### ISSUE TITLE
docsite: make warnings failures

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#638]
I mistyped paths:
- first I used `../deploy/...` in `examples` (relative path instead of absolute path),
- then I misspelled a path (customize instead of kustomize): 

```
/mnt/workspace/pmem-csi_PR-633/examples/memcached.md:44: WARNING: None:any reference target not found: /deploy/customize/memcached/ephemeral
```

It's easy to miss these warnings. Can we turn them into errors which case "make vhtml" to fail?

@intelkevinputnam

**Comment by intelkevinputnam** [comment]
I use these switches to the sphinx build:  -W --keep-going

This will error on warnings, but it will also continue to build. That way we can catch all of them in one go if there are multiple warnings.
