### ISSUE TITLE
operator: publish on operatorhub.io

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#651]
We want PMEM-CSI to be readily available and thus should add our operator to operatorhub.io.

**Comment by avalluri** [comment]
PMEM-CSI operator has been published at OperaroHub.io: https://operatorhub.io/?keyword=pmem&category=Storage

**Comment by pohly** [comment]
We are not completely done yet:
- [ ] https://github.com/intel/pmem-csi/pull/695 still needs to be merged
- [ ] we need figure out how to keep the operator and the installations created through it up-to-date (https://github.com/intel/pmem-csi/pull/695#issuecomment-654036965)
