### ISSUE TITLE
Fix kubebuilder marker issues

### ISSUE THREAD

**Issue by avalluri** [intel/pmem-csi#735]
Due to the below issues, we disable marking a couple of deployment spec fields as mentioned in `https://github.com/intel/pmem-csi/pull/695/files#diff-6dbccdd31f0d920af3f26b2bbb144b09R51-R56`

Fails setting default(+kubebuilder:default=value): 
-   https://github.com/kubernetes-sigs/controller-tools/issues/478

Fails setting min/max for integers:
-   https://github.com/helm/helm/issues/5806

Reenable(replace '-' prefix with '+') markings in code once these upstream issues got fixed.

**Comment by pohly** [comment]
This got resolved by https://github.com/intel/pmem-csi/pull/832
