### ISSUE TITLE
controller failed to connect to node driver

### ISSUE THREAD

**Issue by avalluri** [intel/pmem-csi#766]
PMEM-CSI driver setup fails when running in the cluster where `firewalld` is enabled:

```
$ kubectl  logs -f pmem-csi-intel-com-controller-0 pmem-driver
I1005 03:36:44.304694       1 main.go:67] Version: v0.5.0-rc1-820-g1c288091
I1005 03:36:44.401260       1 server.go:52] Listening for connections on address: /csi/csi-controller.sock
I1005 03:36:44.401663       1 server.go:52] Listening for connections on address: [::]:10000
I1005 03:36:44.401707       1 pmem-csi-driver.go:383] Prometheus endpoint started at http://[::]:10010/metrics
I1005 03:36:45.001440       1 tracing.go:19] GRPC call: /csi.v1.Identity/Probe
I1005 03:36:45.001473       1 tracing.go:20] GRPC request: {}
I1005 03:36:45.005005       1 tracing.go:25] GRPC response: {}
I1005 03:36:45.007182       1 tracing.go:19] GRPC call: /csi.v1.Identity/GetPluginInfo
I1005 03:36:45.007233       1 tracing.go:20] GRPC request: {}
I1005 03:36:45.007357       1 tracing.go:25] GRPC response: {"name":"pmem-csi.intel.com","vendor_version":"v0.5.0-rc1-820-g1c288091"}
I1005 03:36:45.008598       1 tracing.go:19] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I1005 03:36:45.008619       1 tracing.go:20] GRPC request: {}
I1005 03:36:45.008693       1 tracing.go:25] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}},{"Type":{"Service":{"type":2}}}]}
I1005 03:36:45.010334       1 tracing.go:19] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I1005 03:36:45.010357       1 tracing.go:20] GRPC request: {}
I1005 03:36:45.010430       1 tracing.go:25] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":3}}},{"Type":{"Rpc":{"type":4}}}]}
I1005 03:37:33.209435       1 grpc.go:164] VerifyPeerCertificate: DNSName=pmem-node-controller
I1005 03:37:35.152303       1 tracing.go:19] GRPC call: /registry.v0.Registry/RegisterController
I1005 03:37:35.152335       1 tracing.go:20] GRPC request: {"endpoint":"tcp://10.32.0.7:10001","node_id":"sse-tme-cy-03"}
I1005 03:37:35.152519       1 registryserver.go:162] Registering node: sse-tme-cy-03, endpoint: tcp://10.32.0.7:10001
I1005 03:37:35.152539       1 registryserver.go:116] Connecting to node controller: tcp://10.32.0.7:10001
E1005 03:37:36.153820       1 tracing.go:23] GRPC error: failed to register node: Node failed to report volumes: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.32.0.7:10001: connect: no route to host"
```

The node driver could connect to the controller via service-ip, but the controller failed to connect the node where it uses the pod-id.

Disabling the `firewalld`  could able to fix the issue.

I think there might be nothing that could be fixed in the driver code, but is something that should be mentioned in our documentation?.

**Comment by pohly** [comment]
Which distro did this occur on?

"Disabling the firewalld could able to fix the issue." -> "Disabling firewalld fixed the issue.", right?

**Comment by pohly** [comment]
> I think there might be nothing that could be fixed in the driver code, but is something that should be mentioned in our documentation?

We either have to document it as a known issue or redesign PMEM-CSI so that this no longer occurs (https://github.com/intel/pmem-csi/issues/733).

**Comment by avalluri** [comment]
> Which distro did this occur on?
> 
> "Disabling the firewalld could able to fix the issue." -> "Disabling firewalld fixed the issue.", right?

yes.

**Comment by pohly** [comment]
Which distro did this occur on?

**Comment by avalluri** [comment]
> Which distro did this occur on?

fedora 32

**Comment by pohly** [comment]
Another option is the idea that I outlined in https://github.com/intel/pmem-csi/issues/526

**Comment by pohly** [comment]
@avalluri are you sure that firewalld was configured correctly for Kubernetes? Apparently it is difficult to find out exactly which ports need to be opened.

I tried to reproduce this issue. When I just used the ports from https://medium.com/platformer-blog/kubernetes-on-centos-7-with-firewalld-e7b53c1316af the PMEM-CSI node pods didn't come up ("deadline exceeded when creating sandbox"). While checking networking, I found that weavenet needs to connect to port 6783 on each node. With that also opened, PMEM-CSI came up fine, *including* communication both ways between controller and nodes.

FWIW, here's the patch that I tested with:
```
diff --git a/test/setup-fedora-govm.sh b/test/setup-fedora-govm.sh
index cd2efe0b..32950ed6 100755
--- a/test/setup-fedora-govm.sh
+++ b/test/setup-fedora-govm.sh
@@ -68,6 +68,10 @@ EOF
     packages+=" --disableexcludes=kubernetes"
 fi
 
+# Also install and activate firewalld, because that is something that
+# may be active and we want to test with it.
+packages+=" firewalld"
+
 # Sometimes we hit a bad mirror and get "Failed to synchronize cache for repo ...".
 # https://unix.stackexchange.com/questions/487635/fedora-29-failed-to-synchronize-cache-for-repo-fedora-modular
 # suggests to try again after a `dnf update --refresh`, so that's what we do here for
@@ -86,6 +90,32 @@ while ! dnf install -y $packages; do
     fi
 done
 
+# Activate firewalld. Port numbers from https://medium.com/platformer-blog/kubernetes-on-centos-7-with-firewalld-e7b53c1316af
+systemctl unmask firewalld
+systemctl start firewalld
+systemctl enable firewalld
+case "$HOSTNAME" in
+    *master*)
+        firewall-cmd --permanent --add-port=6443/tcp
+        firewall-cmd --permanent --add-port=2379-2380/tcp
+        firewall-cmd --permanent --add-port=10250/tcp
+        firewall-cmd --permanent --add-port=10251/tcp
+        firewall-cmd --permanent --add-port=10252/tcp
+        firewall-cmd --permanent --add-port=10255/tcp
+        firewall-cmd --permanent --add-port=8472/udp
+        firewall-cmd --add-masquerade --permanent
+        ;;
+    *)
+        firewall-cmd --permanent --add-port=10250/tcp
+        firewall-cmd --permanent --add-port=10255/tcp
+        firewall-cmd --permanent --add-port=8472/udp
+        firewall-cmd --permanent --add-port=30000-32767/tcp
+        firewall-cmd --add-masquerade --permanent
+esac
+
+# 6783 added for weavenet.
+firewall-cmd --permanent --add-port=6783/tcp
+
 if $INIT_KUBERNETES; then
     # Upstream kubelet looks in /opt/cni/bin, actual files are in
     # /usr/libexec/cni from
```

So it might be that this issue is invalid and PMEM-CSI works as intended on a fully functional cluster.

**Comment by avalluri** [comment]
> @avalluri are you sure that firewalld was configured correctly for Kubernetes? Apparently it is difficult to find out exactly which ports need to be opened.

I am not sure if it was configured correctly, As I was validating the driver on the latest hardware, I did not spend much time to alter the configuration(though tried enabling few ports) than disabling it.
> 
>  While checking networking, I found that weavenet needs to connect to port 6783 on each node.

Most probably this is what I couldn't figured-out myself.

> With that also opened, PMEM-CSI came up fine, _including_ communication both ways between controller and nodes.
> ...
> 
> So it might be that this issue is invalid and PMEM-CSI works as intended on a fully functional cluster.

Yes, I also agree to close the issue. But the only question is, do we need to mention this in our documentation?

**Comment by pohly** [comment]
> But the only question is, do we need to mention this in our documentation?

I don't think so. There's really not much to say other than "if your CNI plugin doesn't work correctly, then PMEM-CSI may fail".
