### ISSUE TITLE
Sphinx rendering of link text with verbatim markup

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#767]
When the link text is a file name or some other text in backticks, the resulting text in the docsite isn't rendered as a link. Example:
https://intel.github.io/pmem-csi/0.8/docs/install.html#generic

```
See
[`pmem-app-generic-ephemeral.yaml`](/deploy/common/pmem-app-generic-ephemeral.yaml)
for an example.
```

It works fine in GitHub:

See
[`pmem-app-generic-ephemeral.yaml`](/deploy/common/pmem-app-generic-ephemeral.yaml)
for an example.

**Comment by pohly** [comment]
We either have to improve the rendering or avoid this.

@intelkevinputnam: thoughts?

**Comment by intelkevinputnam** [comment]
@pohly I think it's just a matter of tweaking the CSS. I'll take a look.

**Comment by pohly** [comment]
Hmm, still looks like before? Did I break the PR when merging?

**Comment by intelkevinputnam** [comment]
Need to add this to conf.py:

``` python
def setup(app):
    app.add_css_file("override.css")
```

This tells Sphinx that it needs to reference the css file in the HTML output. I'll submit a PR later today to add it.
