### ISSUE TITLE
docsite: EOF handling for operator CRD

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#773]
https://intel.github.io/pmem-csi/0.8/docs/install.html#install-pmem-csi-driver

has an example for creating the custom resource. The copy button stops after `<<EOF` instead of copying everything.

**Comment by pohly** [comment]
CC @intelkevinputnam

**Comment by intelkevinputnam** [comment]
@pohly I'll take a look.

**Comment by intelkevinputnam** [comment]
@pohly In order for this to work in Sphinx you have to use the "ShellSession" type for syntax highlighting. In this case the code block is marked as "console." The "ShellSession" type is a special case that copies everything in the code block except the prompt ("$"). Use "console" in cases where you only want to copy the prompt line and not the lines following (output).

**Comment by pohly** [comment]
I thought `console` and `ShellSession` were synonyms.

> Use "console" in cases where you only want to copy the prompt line and not the lines following (output).

So something like this will not work?

``` ShellSession
$ echo foo
foo
$ echo bar
bar
```

It'll copy the commands (minus the $) *and* the output?

Then we'll really have to be careful about which one we use and how.

**Comment by pohly** [comment]
> It'll copy the commands (minus the $) and the output?

Indeed, it does.

**Comment by intelkevinputnam** [comment]
In GitHub Markdown they are synonyms. The lexer that Sphinx uses doesn't recognize ShellSession, so I used it opportunistically to create a special case to enable this specific behavior.
