### ISSUE TITLE
operator mode, The registrarImage cannot be specified 

### ISSUE THREAD

**Issue by liupeng0518** [intel/pmem-csi#787]
operator mode, The registrarImage cannot be specified,still use the default.

**Comment by liupeng0518** [comment]
release 0.8 version.

**Comment by avalluri** [comment]
The driver registrar image field mentioned(`registrarImage`) in the documentation was wrong. It supposed to be `nodeRegistrarImage`. https://github.com/intel/pmem-csi/pull/790 fixes this.

**Comment by pohly** [comment]
@liupeng0518 was this not caught by validation when doing `kubectl create` with input that contains an unknown field?

**Comment by pohly** [comment]
It indeed isn't caught, I tried.

@avalluri is that expected?

**Comment by avalluri** [comment]
> It indeed isn't caught, I tried.
> 
> @avalluri is that expected?

Generated CRD uses `x-kubernetes-preserve-unknown-fields: true` where the API server prunes the unknown fields silently without any validation errors. If we make the unknown fields as validation error we should stop setting this field.

**Comment by pohly** [comment]
Let's continue in https://github.com/intel/pmem-csi/issues/795
