### ISSUE TITLE
operator CRD: warn about unknown fields

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#795]
As noticed in https://github.com/intel/pmem-csi/issues/787, there's currently no warning when the YAML file for a CR contains unsupported fields. This is confusing for users.

**Comment by pohly** [comment]
@avalluri wrote:
> Generated CRD uses x-kubernetes-preserve-unknown-fields: true where the API server prunes the unknown fields silently without any validation errors. If we make the unknown fields as validation error we should stop setting this field.

Can you think of a reason why we should silently remove unknown fields?

It may be useful if a once valid field gets removed and ignoring it is fine, but I don't think we have such a case in PMEM-CSI, so IMHO we should warn about unknown fields during validation.

**Comment by avalluri** [comment]
> Can you think of a reason why we should silently remove unknown fields?

This was the default behavior in `v1beta1` CRD API, moving to `v1`  treats unknown fields as a validation error. I think `v1beta1` is a bit obsolete and we should use CRD `v1` anyways.

**Comment by pohly** [comment]
So you can't think of a reason to ignore unknown fields either?

Let's switch to v1 then to resolve this issue.
