### ISSUE TITLE
YAML setup: non-default namespace setup is broken

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#834]
```
$ make start
...
$ test/setup-deployment.sh
INFO: deploying from /nvme/gopath/src/github.com/intel/pmem-csi/deploy/kubernetes-1.19/lvm/testing
Error from server (NotFound): error when creating "STDIN": namespaces "pmem-csi" not found
Error from server (NotFound): error when creating "STDIN": namespaces "pmem-csi" not found
```

**Comment by pohly** [comment]
Where is the namespace supposed to be created?

**Comment by pohly** [comment]
I'm testing with my own branch ATM, so it could be that I broke something.

**Comment by pohly** [comment]
I think it's creating the secrets that fails, because the namespace only gets created later via the .yaml file.

But how does that work in our CI?

**Comment by pohly** [comment]
> But how does that work in our CI?

It works because tests like `direct-testing E2E [Testpattern: Dynamic PV (ext4)] dax should support MAP_SYNC` still use "default" as namespace.

**Comment by pohly** [comment]
The instructions in install.md are also broken: users are told to create secrets first, which can't work because the namespace does not exist yet. If they create the namespace first, then `kubectl create -f deploy/kubernetes-1.19/pmem-csi-lvm.yaml` fails with `Error from server (AlreadyExists): error when creating "deploy/kubernetes-1.19/pmem-csi-lvm.yaml": namespaces "pmem-csi" already exists`.

**Comment by pohly** [comment]
> I'm testing with my own branch ATM, so it could be that I broke something.

Also occurs with current "devel".

**Comment by pohly** [comment]
@avalluri : my conclusion is that we can't create the namespace via the deployment YAML files. Do you agree?

I'm working on reverting that.

**Comment by avalluri** [comment]
> I think it's creating the secrets that fails, because the namespace only gets created later via the .yaml file.
> 
> But how does that work in our CI?

All driver tests runs in default namespaces as earlier, That was the reason it didn't reveal, My initial script changes were creating the namespace. But later I moved that to YAMLs as I was thinking that this script is supposed to used by only tests but not by the end user.  That resulted in this issue.

**Comment by avalluri** [comment]
> @avalluri : my conclusion is that we can't create the namespace via the deployment YAML files. Do you agree?

I couldn't decide which is the right approach, I referred the other existing YEMLs, for example `cert-manager` it creates the namespace from its deployment YAMLs. So I leaned towards creating the namespace. But you are right  this might not work for us because of the secret creation, else we need to move the secret creation part to post driver deployment.

**Comment by pohly** [comment]
> But you are right this might not work for us because of the secret creation, else we need to move the secret creation part to post driver deployment.

That's indeed the key difference compared to cert-manager: in our case, the namespace is shared between different entities which get created and destroyed independently. That implies that there is no single entity which can own that namespace.

The same problem may exist for the operator, see https://github.com/intel/pmem-csi/issues/835
