### ISSUE TITLE
Kubernetes 1.20

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#853]
Let's add testing against Kubernetes 1.20.

**Comment by avalluri** [comment]
After reenabling `EndpointSlice` feature gate and moving to calico cni I could able to bring up the v1.20 test cluster.
And tested the basic usecases of running the operator, driver and provision the PMEM volumes seems work with no issues.

I need to still needs complete validation by running the PMEM-CSI E2E testsuite.
