### ISSUE TITLE
filesystems not properly aligned for hugepages

### ISSUE THREAD

**Issue by krisiasty** [intel/pmem-csi#942]
While browsing the the source code I noticed [here](https://github.com/intel/pmem-csi/blob/16124c432bd8a3884f96238cc2485b580dc43fc9/pkg/pmem-csi-driver/nodeserver.go#L643) that the xfs filesystem is created and later mounted in a way that do not support proper alignment for 2m hugepages.

According to numerous sources like [here](https://pmem.io/2018/05/15/using_persistent_memory_devices_with_the_linux_device_mapper.html), [here](https://software.intel.com/content/www/us/en/develop/articles/speeding-up-io-workloads-with-intel-optane-dc-persistent-memory-modules.html), or [here](https://software.intel.com/content/www/us/en/develop/articles/pmem-performance-under-xfs-and-ext4-filesystems.html) the mkfs.xfs call should contain the following parameters:
```mkfs.xfs -f -i size=2048 -d su=2m,sw=1 -m reflink=0 /dev/pmemXYZ ```

The data block size is by default 4k, so the `-b size=4096` is usually not necessary, but you might want to keep to be sure.

There is additional step necessary (adjusting xfs extsize to 2m) **AFTER** the filesystem is mounted:
```xfs_io -c "extsize 2m" /mountpoint```

The first source mentioned above also recommends additional arguments for mkfs.ext4, but the other two don't, so I'm not sure if this is still necessary in recent kernels:
`mkfs.ext4 -b 4096 -E stride=512 -F /dev/pmem0`

**Comment by pohly** [comment]
We have a PR open for this: https://github.com/intel/pmem-csi/pull/499

It got a bit stuck because we weren't sure how to test it. Do you know of a reliable way to check that huge pages are enabled correctly?

**Comment by okartau** [comment]
yes I started the work in #499 which contains the options add part, but it does not add xfs_io part.
As we agreed we try to add testing together with code change, I attempted it, but counting hugepage faults in kernel appeared to be not well deterministic, as I got results either ways. Also, the results were not consistent ext4 vs xfs cases, I think I tried to write results down in PR comments. I need to revisit this PR, the testing code part also needs more. I will add xfs_io part there as well.

**Comment by krisiasty** [comment]
The extsize tuning via xfs_io is important. I have no experience with ext4 on pmem, so not sure if `-E stride=512` is necessary (probably is). I assume the information from the sources I provided is valid. If you need to better understand testing methodology, I think you might want to reach out internally to Eduardo Berrocal at Intel (one of the authors of the articles I referred to).
I recall I did some tests in the past based on the information from pmdk.io article. Make sure you have debugfs mounted properly first (or tracefs in RHEL8-based systems). I don't have access to any systems I could experiment on right now so can't confirm that though.
Anyway, the main goal of creating this issue was to be sure we have the filesystem structures aligned properly. It is still up to system administrator to enable and properly configure huge pages if needed.

**Comment by pohly** [comment]
Resolved via https://github.com/intel/pmem-csi/pull/499
