### ISSUE TITLE
Operator Hub: next stability level

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#960]
We are listed with an "alpha" channel and without the "Full Lifecycle" capability. Depending on the definition of the later, we should support it.

We also should replace "alpha". What's the next level? "beta"?

**Comment by pohly** [comment]
Let's replace "alpha" with "stable".

**Comment by avalluri** [comment]
As per guiding questions listed at https://sdk.operatorframework.io/docs/advanced-topics/operator-capabilities/operator-capabilities/#level-3---full-lifecycle, I feel we not yet support the below to move to "Full Lifecycle":

```
Does your Operator allow adding/removing read-only slave instances of your Operator?
Does your operand have a Liveness probe?
Does your operand have a Readiness probe which will fail if any aspect of the operand is not ready? e.g. if the connection to the database fails.
Does your operator create a PodDisruptionBudget resource for your operand pods?
```

**Comment by pohly** [comment]
> Does your Operator allow adding/removing read-only slave instances of your Operator?

Any idea what that means?

> Does your operand have a Liveness probe?

Can be added.

We could add the livenessprobe sidecar, but adding a HTTP endpoint is easier.

> Does your operand have a Readiness probe which will fail if any aspect of the operand is not ready? e.g. if the connection to the database fails.

Same here.

> Does your operator create a PodDisruptionBudget resource for your operand pods?

Not yet, to be added.

**Comment by pohly** [comment]
> Does your Operator allow adding/removing read-only slave instances of your Operator?

This starts to make more sense when replacing "of your Operator" with "of your operand". In the context of databases, this could be a read-only, internally consistent snapshot of the database for backup purposes.

**Comment by pohly** [comment]
> Does your operator create a PodDisruptionBudget resource for your operand pods?

This only makes sense for the controller, and only if we enable replication. For that we need to know how the scheduler will reach the controller - through the service or through an external load balancer?

**Comment by pohly** [comment]
> > Does your operator create a PodDisruptionBudget resource for your operand pods?
> 
> This only makes sense for the controller, and only if we enable replication. For that we need to know how the scheduler will reach the controller - through the service or through an external load balancer?

For OpenShift, access to the scheduler extender and the webhook is done through the service, so replication would make sense to avoid outages during a rolling update. I started the implementation (see last commit in https://github.com/intel/pmem-csi/pull/1025), I am just not sure whether we should tackle that for 1.0.

**Comment by pohly** [comment]
PR #1025 was merged. What we haven't done yet is bump the capability in the bundle meta data.

@avalluri once v1.0.0 is released, can you take care of submitting the operator update to Operator Hub and while doing that, increase the capability to "Full Lifecycle"?

**Comment by pohly** [comment]
We might also have to consider how testing will work once v1.0.0 is the base version and testing happens on OpenShift: then the base bundle is not the one we published on Operator Hub and the base image not intel/pmem-csi-driver:v1.0.0.

**Comment by pohly** [comment]
> once v1.0.0 is released, can you take care of submitting the operator update to Operator Hub and while doing that, increase the capability to "Full Lifecycle"?

Done: https://operatorhub.io/operator/pmem-csi-operator

> We might also have to consider how testing will work once v1.0.0 is the base version and testing happens on OpenShift: then the base bundle is not the one we published on Operator Hub and the base image not intel/pmem-csi-driver:v1.0.0.

Fixed by https://github.com/intel/pmem-csi/pull/1035
