### ISSUE TITLE
Kata Containers support broke

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#987]
Kata Containers support has to be tested manually because our CI cannot run Kata Containers (nested virtualization too slow). We haven't done that in a while and Kata Containers support indeed doesn't work anymore.

- CreateVolume does not prepare a VolumeContext for NodePublishVolume, which then skips the additional steps needed for Kata Containers.

This leads to "dax not supported" errors when running our E2E tests and `umount: /var/lib/pmem-csi.intel.com/mount/pvc-9e-7092cd8178474c5c4b10abab50defac8fc868cf874d74303c3841c66: no mount point specified.` during NodeUnpublishVolume.

- parted is needed inside the driver image but wasn't installed anymore.

- NodeUnpublishVolume probably also isn't idempotent when the volume was prepared for Kata Containers. `nodeUnpublishKataContainerImage` should have proceeded even without the mount point.

**Comment by pohly** [comment]
I'm testing with:
```
TEST_KATA_CONTAINERS_VERSION=1.12.1 make push-images test_e2e TEST_E2E_FOCUS=direct-testing.*Kata
```

The test pod fails to start:
```
• Failure [19.200 seconds]
direct-testing
/nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/deploy/deploy.go:1369
  E2E
  /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/deploy/deploy.go:1354
    Kata Containers
    /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/storage/csi_volumes.go:217
      [Testpattern: Dynamic PV (ext4)] dax
      /nvme/gopath/pkg/mod/k8s.io/kubernetes@v1.20.2/test/e2e/storage/testsuites/base.go:129
        should support MAP_SYNC [It]
        /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/storage/dax/dax.go:125

        Jun  9 10:31:11.974: running pod
        Unexpected error:
            <*errors.errorString | 0xc000711950>: {
                s: "pod ran to completion",
            }
            pod ran to completion
        occurred

        /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/storage/dax/dax.go:299
...

$ kubectl describe -n dax-8511 pods/dax-volume-test-kata
Name:         dax-volume-test-kata
Namespace:    dax-8511
Priority:     0
Node:         pmem-csi-pmem-govm-worker2/172.17.0.4
Start Time:   Wed, 09 Jun 2021 10:21:19 +0200
Labels:       io.katacontainers.config.hypervisor.memory_offset=2147483648
...
Containers:
  dax-container:
    Container ID:  containerd://029ab23cf7d1fcf26e4aa3e89fbd4c00d9177bdef8e4e71264394a24950d729b
    Image:         172.17.42.1:5001/pmem-csi-driver:canary
    Image ID:      172.17.42.1:5001/pmem-csi-driver@sha256:ff9e8af2b93b166c89f942cfa89a4a770129977254792685b7beb475ed77d4fc
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
      1000000
    State:          Terminated
      Reason:       StartError
      Message:      failed to create containerd task: QMP command failed: not enough space, currently 0x10000000 in use of total space for memory devices 0x37b00000: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 01:00:00 +0100
      Finished:     Wed, 09 Jun 2021 10:21:24 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      pmem-csi.intel.com/scheduler:  1
    Requests:
      pmem-csi.intel.com/scheduler:  1
    Environment:                     <none>
    Mounts:
      /mnt from vol1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bt2kg (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  vol1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  direct-testing-pmem-csi-kataz75bd
    ReadOnly:   false
  default-token-bt2kg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-bt2kg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  katacontainers.io/kata-runtime=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  40s   default-scheduler  Successfully assigned dax-8511/dax-volume-test-kata to pmem-csi-pmem-govm-worker2
  Normal   Pulling    37s   kubelet            Pulling image "172.17.42.1:5001/pmem-csi-driver:canary"
  Normal   Pulled     35s   kubelet            Successfully pulled image "172.17.42.1:5001/pmem-csi-driver:canary" in 1.407684299s
  Normal   Created    35s   kubelet            Created container dax-container
  Warning  Failed     35s   kubelet            Error: failed to create containerd task: QMP command failed: not enough space, currently 0x10000000 in use of total space for memory devices 0x37b00000: unknown
```

**Comment by pohly** [comment]
Fixes that are needed to get to that point are in: https://github.com/pohly/pmem-CSI/tree/fix-kata-containers-support

**Comment by pohly** [comment]
I'm using `TEST_KATA_CONTAINERS_VERSION=1.12.1` because that is the latest tag in https://github.com/kata-containers/packaging/tree/master/kata-deploy

I am not sure yet where those files are for newer releases like the current 2.1.0. It's not obvious from the release notes and https://hub.docker.com/r/katadocker/kata-deploy which still links to the obsolete kata-containers/packaging.

**Comment by pohly** [comment]
With Kata Containers 2.1.0, I get the same `Error: failed to create containerd task: QMP command failed: not enough space, currently 0x8000000 in use of total space for memory devices 0x37b00000: unknown` error.

**Comment by pohly** [comment]
@devimc: see above ^^^

**Comment by pohly** [comment]
Our testing so far relied on full E2E testing with Kata Containers. This particular error could have been caught by testing the volume without the Kata Containers runtime - I'm on it...

**Comment by pohly** [comment]
Is `io.katacontainers.config.hypervisor.memory_offset=2147483648` still valid?

Re-reading the documentation written by my former self, the `not enough space` is exactly what one gets when not having that label or using the wrong value. I need to double check whether we perhaps have bumped up our image size, but my suspicion now is more towards the label not having the desired effect anymore.

**Comment by devimc** [comment]
> Is io.katacontainers.config.hypervisor.memory_offset=2147483648 still valid?

it is, https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/annotations/annotations.go#L146

**Comment by pohly** [comment]
@devimc Is there end user documentation for these annotations that I can link to?

**Comment by devimc** [comment]
@pohly  https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md

**Comment by pohly** [comment]
It's related to the volume size. With LVM it started the pod, presumably because LVM volumes can be smaller (will check later). I'm now running into a different issue related to Kata Containers: we rely on kubelet changing the ownership of the volumes for us because we want to run the app as non-root, to demonstrate best practices and ensure that it works.

This is triggered by this part in the Pod spec:
```
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
```

With Kata Containers, /mnt is not writable by that user, causing the daxtest to fail when running

@devimc is this a known issue with Kata Containers?

Then during test shutdown, there's another issue: deleting the pod hangs.

```
Events:
  Type     Reason         Age                   From               Message
  ----     ------         ----                  ----               -------
  Normal   Scheduled      14m                   default-scheduler  Successfully assigned dax-8162/dax-volume-test-kata to pmem-csi-pmem-govm-worker2
  Normal   Pulling        14m                   kubelet            Pulling image "172.17.42.1:5001/pmem-csi-driver:canary"
  Normal   Pulled         14m                   kubelet            Successfully pulled image "172.17.42.1:5001/pmem-csi-driver:canary" in 1.559117227s
  Normal   Created        14m                   kubelet            Created container dax-container
  Normal   Started        14m                   kubelet            Started container dax-container
  Warning  FailedKillPod  102s                  kubelet            error killing pod: [failed to "KillContainer" for "dax-container" with KillContainerError: "rpc error: code = DeadlineExceeded desc = context deadline exceeded", failed to "KillPodSandbox" for "d4a397ac-9b27-4500-b3e2-89d33c379246" with KillPodSandboxError: "rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
  Normal   Killing        101s (x2 over 6m12s)  kubelet            Stopping container dax-container
```

This is with Kata Containers 2.1.0, Kubernetes 1.20, containerd 1.3.7. Nothing obvious in the systemd journal on the node.

@devimc any suggestions what I should look for?

**Comment by pohly** [comment]
> https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md

According to that, `io.katacontainers.config.hypervisor.memory_offset` is an `uint32`. Doesn't that limit the size of NVDIMM per pod to 4GB?

The current value in the test is 2147483648 = 2GB. That should be large enough. With direct mode (the one which is triggering the error), volumes are:
```
[root@pmem-csi-pmem-govm-worker1 fedora]# lsblk 
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    252:0    0  400G  0 disk 
└─vda1 252:1    0  400G  0 part /
vdb    252:16   0  372K  0 disk 
pmem0  259:0    0    1G  0 disk 
```

I.e. 1GB that need to be mapped into the VM. I'm not sure why that is failing.

With LVM mode, the volumes are 110MB and the image file itself 100MB. That works.

**Comment by pohly** [comment]
I tried changing the value, but the error message remains the same:
```
Labels:       io.katacontainers.config.hypervisor.memory_offset=1073741824
...
  Warning  Failed     16s   kubelet            Error: failed to create containerd task: QMP command failed: not enough space, currently 0x8000000 in use of total space for memory devices 0x37b00000: unknown
```

Should something change when changing the label?

**Comment by pohly** [comment]
> Is `io.katacontainers.config.hypervisor.memory_offset=2147483648` still valid?
> 
> Re-reading the documentation written by my former self, the `not enough space` is exactly what one gets when not having that label or using the wrong value.

It's not supposed to be a label. It must be an annotation. Will fix in PMEM-CSI.

When using an annotation with a freshly installed Kata Containers, I now get:
```
$ kubectl describe pods/my-csi-kata-app
...
  Warning  FailedCreatePodSandBox  0s (x11 over 10s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: annotation io.katacontainers.config.hypervisor.memory_offset is not enabled: unknown
```

I discussed this briefly with @devimc yesterday and it's related to the `/etc/containerd/config.toml` file. That file has the necessary `pod_annotations = ["io.katacontainers.*"]` but that alone doesn't seem to be enough. I filed a bug: https://github.com/kata-containers/kata-containers/issues/2002

**Comment by pohly** [comment]
> > https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md
> 
> According to that, `io.katacontainers.config.hypervisor.memory_offset` is an `uint32`. Doesn't that limit the size of NVDIMM per pod to 4GB

I created an enhancement request for this: https://github.com/kata-containers/kata-containers/issues/2006

**Comment by devimc** [comment]
>   I created an enhancement request for this: kata-containers/kata-containers#2006

https://github.com/kata-containers/kata-containers/pull/2017 fixes this issue, thanks

**Comment by pohly** [comment]
https://github.com/kata-containers/kata-containers/issues/2018 tracks the pod shutdown issue.

**Comment by devimc** [comment]
@pohly - I was working on a solution to automagically calculate the memory offset required for pmem devices, but this is not possible since the VM is started when the first container (sandbox or pause container) is created, so when the pmem container (workload that uses the pmem device) is created the offset can't be changed

**Comment by devimc** [comment]
@pohly 

> kata-containers/kata-containers#2018 tracks the pod shutdown issue.

https://github.com/kata-containers/kata-containers/pull/2066 fixes this

**Comment by pohly** [comment]
> @pohly - I was working on a solution to automagically calculate the memory offset required for pmem devices, but this is not possible since the VM is started when the first container (sandbox or pause container) is created, so when the pmem container (workload that uses the pmem device) is created the offset can't be changed

What's the downside of making the offset very large? If there is none, then we could make it large enough by default for any potential PMEM per node configuration and users won't have to change it.
