### ISSUE TITLE
Deploying pmem csi driver with ndctl mode sector

### ISSUE THREAD

**Issue by KiChoudhary** [intel/pmem-csi#991]
I want to deploy the pmem csi driver where the ndctl mode of my pmem devices is "sector". 
Throughout the document, the fsdax mode is recommended. I tried manually configuring the pmem devices before the deployment prcoess, this does not allow my node-setup daemonset to schedule the nodes and run the pods. 

Kindly recommend a method that I can follow to achieve the objective. 
Thanks

**Comment by pohly** [comment]
We removed support for sector mode in commit 35de1446b312953f3500c3a68b4502bcca876ad2 to simplify PMEM-CSI and because the [upstream documentation](https://pmem.io/ndctl/ndctl-create-namespace.html) makes it sound like the mode shouldn't be needed anymore:
> Use this mode to host legacy filesystems that do not checksum metadata or applications that are not prepared for torn sectors after a crash. Expected usage for this mode is for small boot volumes. This mode is compatible with other operating systems.

App Direct enabled applications definitely don't need it. For plain IO it might make sense despite the somewhat dismissive description above: although ext4 and XFS are both not legacy filesystems, torn sector writes can happen with them and applications might have a problem with that.

May I ask what your motivation is for using sector mode? We could bring back support for it, we just need to understand what the priority is.

**Comment by KiChoudhary** [comment]
This is critical for databases applications otherwise data will be left corrupted 

>  all I/O done against persistent memory is done at cache line granularity. This means that all I/O operations are converted by the driver into memory copies. Because the x86 architecture only guarantees write atomicity for 8 bytes at a time, applications and file systems that rely on write atomicity at the block/sector level can get their data corrupted by torn sectors in the event of a crash or power failure.
> 
> To avoid such a scenario, we can create namespaces in sector mode. In this mode, the driver maintains a data structure called the Block Translation Table (BTT) to make sure torn sectors do not happen. To learn more about BTT, read the article Using the Block Translation Table for sector atomicity. One of the implications of using sector mode is that all I/O needs to go through the driver, which means that context switches to the OS are again inevitable.

**Comment by KiChoudhary** [comment]
> So you want to use PMEM as replacement for a local SSD? Is that just theoretical or are you planning some real deployments?

This is definitely for real time deployment. And the PMEMs will coexist along with the SSDs

**Comment by KiChoudhary** [comment]
Hi, I just wanted to ask is it possible to add the sector mode, if yes, can I rely on some timeline ?

**Comment by pohly** [comment]
It's not going to make it for the upcoming 1.0.0 release (due June or July). We don't have a plan for next release after that yet.

Can you share some more details about the cluster(s) you intend to deploy on (in particular, number of nodes and amount of PMEM) with me via private email (patrick.ohly at intel.com)? That'll help prioritize this feature request. Do you already work with someone from Intel on this deployment?

**Comment by KiChoudhary** [comment]
I have mailed you the details on the provided email address. Thanks.

**Comment by pohly** [comment]
Thanks! It sounds like this is more like an academic exercise. I'm very curious whether your experiment will show a significant advantage of using PMEM as storage vs. SSDs. However, until we know that, support for sector mode and  traditional IO in general remain low priority for PMEM-CSI.

What you can do in the meantime is to prepare volumes manually on each of your nodes and mount them under a well-known location, like "/pmem". Then in your pods, request access to that volume with a hostPath volume entry. That way you don't need PMEM-CSI.

**Comment by KiChoudhary** [comment]
Hi Patrick,

May I know if there's any plan to include the above stated requirements in
a future release.

It's not any academic exercise. Our product release depends on these
requirements. If it's feasible we can set up a call as well. This product
is being designed at HPE.

Thanks and regards
